"""Append-only evidence synthesis; no model evaluation, fitting or simulation."""
from common import *
import copy

def main():
 assert not (HERE/'RELEASE.json').exists(),'Release already published; do not overwrite'
 base=load(BASE/'objects'/f'{BASE_SHA}.json');reg=copy.deepcopy(base)
 reg['version']='0.2.0';reg['title']='Project Genesis Biological Neural Specification v0.2'
 verified=load(HERE/'DEPENDENCY_VERIFICATION.json')['packages']
 for name,(folder,_) in PACKAGES.items():
  for suffix,filename in [('report','REPORT.md'),('package','PACKAGE_MANIFEST.json')]:
   p=ROOT/'research'/folder/filename
   reg['sources'][f'v02.{name}.{suffix}']={'path':str(p.relative_to(ROOT)),'sha256':sha(p),'kind':'independent_evidence','section':'Completed post-v0.1 evidence; not an independent biological replication. Full report/package.'}
 additions=[]
 def claim(cid,category,status,scope,statement,study,allowed,prohibited,conflicts=()):
  additions.append({'id':cid,'kind':'claim','category':category,'status':status,'scope':scope,'statement':statement,'layer':'biological','evidence_refs':[f'v02.{study}.report',f'v02.{study}.package'],'supersedes':[],'known_conflicts':list(conflicts),'unsupported_extrapolations':prohibited,'allowed_scientific_wording':[allowed],'prohibited_scientific_wording':prohibited})
 FACT,APPROX,HYP,ENG,PRODUCT=base['categories']
 claim('visual.stage4.gate-a',ENG,'not_supported','Frozen Stage-4 physical visual-stimulus model, Gate A','Gate A NOT SUPPORTED: 0/90 prospectively tested root/level/primary-sensitivity ordering groups satisfy all qualitative constraints. This is a negative result for the frozen computational assumptions, not absence of looming-sensitive physiology in flies.','stage4','The frozen model did not establish LPLC2 expansion selectivity.',['Genesis detects looming.','The model has threat, fear, escape or avoidance capability.'])
 claim('visual.stage4.gate-b',ENG,'not_tested','Frozen Stage-4 descending propagation, Gate B','Gate B NOT TESTED because Gate A failed. Anatomical connectivity does not establish functional descending propagation.','stage4','No descending-response claim was tested.',['An anatomical route validates an escape response.'])
 claim('visual.diagnostic.constraints',FACT,'constrained','Independent physiology versus frozen visual-boundary simplifications','PARTIAL MECHANISTIC CONSTRAINT — MORE DATA REQUIRED. Independent assays contradict a universal strict polarity split and zero stationary-flash response restriction; geometry and observation mappings remain unresolved. Assay-specific evidence does not supply a replacement physiological kernel.','diagnostic','Several frozen visual-boundary simplifications are contradicted or unresolved.',['A coordinate flip inferred from Stage-4 outputs is physiological calibration.','Tm9 calcium validates T4/T5 voltage.'])
 claim('visual.diagnostic.representation',HYP,'unresolved','Replacement LPLC2 representation after diagnostic','No replacement LPLC2 representation, branch coupling magnitude, root-specific sign map or observation operator was selected. Local APL findings do not identify LPLC2 parameters.','diagnostic','No replacement LPLC2 representation was selected.',['Local APL coefficients identify LPLC2 conductance.','Compartmental LPLC2 physiology is calibrated.'])
 claim('visual.t4t5.direct-physiology',FACT,'constrained','Direct T4/T5 whole-cell source preparations','Direct signed somatic voltage, spatial/polarity/temporal response restrictions and source identity limits are established. Nonpreferred-polarity response is not universally absent. Voltage, calcium and recording ordinals remain distinct from rates, flies and roots.','boundary','Direct physiological restrictions are assay-specific.',['All nonpreferred contrast produces excitation.','A recording ordinal identifies a fly or a FlyWire root.'])
 claim('visual.t4t5.boundary-identification',APPROX,'partial_constraint','Frozen T4/T5 Visual Boundary Identification comparison','PARTIAL VISUAL BOUNDARY CONSTRAINT. Conditional flash-selected prediction generalizes unevenly and fails on important motion families. No general T4/T5 boundary or calibrated root-specific operator is identified; explicit precursor necessity is not established.','boundary','No general visual boundary or necessary explicit precursor circuit was identified.',['A flash fit validates all visual stimuli.','Mi/Tm/CT1 simulation is proven necessary.'])
 claim('visual.empirical.interface',APPROX,'supported_limited_empirical_scope','Frozen T4/T5 empirical interface v0.1.0','LIMITED EMPIRICAL INTERFACE SUPPORTED: 6637 measured waveforms, 14/40 passing registered comparisons; only two T5 dark-flash duration interpolation strata and conditional exact-condition templates. No cross-family prediction or mechanistic precursor reconstruction.','empirical','A restricted empirical voltage interface is supported.',['A universal T4/T5 mechanistic model is validated.','Empirical retrieval reconstructs omitted precursor circuitry.','Predictive errors establish visual perception.'])
 claim('visual.empirical.support-domain',ENG,'restricted','Frozen empirical support categories and UNKNOWN policy','DIRECTLY MEASURED is exact recording/condition retrieval, not held-out validation. INTERPOLATION-SUPPORTED requires a passing stratum and strict source-tested one-axis bracket. Conditional class templates remain WEAKLY SUPPORTED. Out-of-distribution or unsupported individual queries return UNKNOWN/null, never a fabricated zero response.','empirical','Support belongs to full source/frame/observation/physical tuples, not marginal ranges.',['Unknown physiology is zero physiology.','All points inside marginal ranges are validated.'])
 claim('visual.empirical.observation',ENG,'restricted','Frozen empirical voltage export and observation conversion','Export is mean baseline-subtracted somatic voltage in mV, 0–500 ms on the documented 1 ms grid. Source resampling does not add physiological temporal resolution. Conversion to calcium, spikes, release, synaptic current or model rate is unidentified and prohibited for this release.','empirical','Empirical somatic mV is an observation quantity.',['Somatic mV equals terminal release, synaptic current, calcium, spikes or model rate.'])
 claim('visual.empirical.identity-transfer',ENG,'unresolved','Frozen empirical recording/class versus root/subtype/column/fly transfer','Named recording retrieval and conditional T4/T5 class templates do not identify subtype, column, fly or FlyWire-root physiology. Source RF/PD localization is conditional; retinal/head/root registration and a universal pixel-angle transform remain unknown.','empirical','No unsupported root/subtype/column/fly transfer is admitted.',['Recording-held-out validation is fly-held-out validation.','Anatomical type identity supplies recording-specific physiology.'])
 claim('visual.empirical.stage4-ood',ENG,'out_of_distribution','Post-freeze static audit of all 16 frozen Stage-4 physical conditions','All 16 Stage-4 physical conditions remain OUT OF DISTRIBUTION / UNKNOWN under the frozen empirical interface. This is a static physical-descriptor support audit, not a Stage-4 rerun or LPLC2 evaluation.','empirical','All 16 old physical conditions lack validated empirical support.',['A measured grating family validates arbitrary angular gratings.','OOD audit establishes LPLC2 failure or success under a new model.'])
 reg['entries'].extend(additions);reg['entry_hashes']={e['id']:digest(e) for e in reg['entries']}
 reviews=[{'entry_id':e['id'],'entry_sha256':digest(e),'reviewer':'Codex evidence/package verification under explicit user-authorized v0.2 synthesis; no external peer-review claim','reviewed_at':now(),'rationale':'Matches the user-specified narrow conclusion and verified finalized package; preserves historical classifications, unknown physiology and capability restrictions. See REVIEW_AUTHORIZATION.md.','independent_evidence_refs':e['evidence_refs'],'supersedes':e['supersedes'],'scope':e['scope']} for e in additions]
 # Write exact canonical bytes so object filename is its file SHA (no trailing newline).
 h=digest(reg);p=HERE/'objects'/f'{h}.json';p.parent.mkdir(exist_ok=True);p.write_bytes(canonical(reg))
 write('ADMISSION_REVIEWS.json',reviews)
 write('REGISTRY_POINTER.json',{'path':str(p.relative_to(HERE)),'sha256':h})
 write('APPEND_ONLY_DIFF.json',{'base_registry_sha256':BASE_SHA,'new_registry_sha256':h,'inherited_entries':len(base['entries']),'added_entries':{e['id']:digest(e) for e in additions},'modified_entries':[],'removed_entries':[],'new_sources':sorted(set(reg['sources'])-set(base['sources'])),'historical_sections_unchanged':['studies','identity','neurons_artifact','stage_anatomy','literature','stage4_contract'],'new_capabilities':0,'new_anatomy_owners':0})
 caps=[{'id':e['id'],'status':e['status'],'inherited_entry_sha256':digest(e),'scope':e['scope'],'validated_biological_model_capability':e['id']=='capability.associative_appetitive_learning'} for e in base['entries'] if e['kind']=='capability']
 for name in ['avoidance','escape','visual_perception','looming_detection_in_Genesis']:
  caps.append({'id':'capability.'+name,'status':'unsupported','inherited_entry_sha256':None,'scope':'No capability admission; explicit prohibition in v0.2 user-authorized governance','validated_biological_model_capability':False})
 write('CAPABILITY_REGISTRY.json',{'base_registry_sha256':BASE_SHA,'registry_sha256':h,'capabilities':caps,'only_validated_capability':'capability.associative_appetitive_learning','threat_note':'Historical threat_behavior=not_tested retained. New frozen visual Gate A failed; no threat/avoidance capability follows.','action_selection':'not_validated','capability_additions_are_prohibitions_not_new_capabilities':True})
 stages=[('stage4','Gate A NOT SUPPORTED for frozen model; Gate B NOT TESTED','Test physically evoked selectivity before descending interpretation.','Which boundary/model assumptions fail, and which physiology is missing?'),('diagnostic','PARTIAL MECHANISTIC CONSTRAINT — MORE DATA REQUIRED','Diagnose the negative result with independent physiology rather than retuning against it.','Can direct T4/T5 data identify a general replacement boundary and coordinate map?'),('boundary','PARTIAL VISUAL BOUNDARY CONSTRAINT','Acquire direct T4/T5 measurements and test cross-stimulus prediction.','Can limited empirical observations provide honest bounded outputs without a general mechanism?'),('empirical','LIMITED EMPIRICAL INTERFACE SUPPORTED','Assess measurement coverage and low-assumption empirical retrieval/prediction.','Coverage, observation conversion and root/coordinate transfer remain insufficient for old LPLC2 stimuli.')]
 write('RESEARCH_LINEAGE.json',{'nodes':[{'id':n,'classification':c,'motivation':why,'unresolved':gap,'package':verified[n],'negative_results_first_class':True} for n,c,why,gap in stages],'edges':[{'from':a,'to':b,'relation':'motivated_by_unresolved_question_not_capability_upgrade'} for a,b in zip([x[0] for x in stages],[x[0] for x in stages][1:])],'shared_measurements_are_not_independent_replication':True})
 write('CANONICAL_IDENTITY_REFERENCES.json',{'ownership':'reference_only','registry_base':'research/genesis-brain-spec-v0.1','identity':base['identity'],'neurons_artifact':base['neurons_artifact'],'canonical_source':base['sources']['identity'],'shared_rows_source':base['sources']['shared-rows'],'shared_counts':{'KC_MBON07':4622,'KC_MBON11':1053},'physiology_composition':'blocked_unresolved_rules','new_rows_owned':0,'stage4_anatomy':'referenced by verified experiment package only; not copied or admitted as a new physiology operator'})
 print(json.dumps({'registry_sha256':h,'inherited':len(base['entries']),'added':len(additions)}))
if __name__=='__main__':main()
