import {tailFaultPool} from './support/lease-tail-fault.ts';
import {leaseClock} from './support/lease-clock.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import pg from 'pg';
import {spawn} from 'node:child_process';
import {continuousFixture,manual,sleep} from './support/continuous-fixture.ts';
import {oneShotFixture,authorize} from './support/one-shot-fixture.ts';
import {ProductFallback} from '../core/v2/planner.ts';
import {eventSchema,LOCAL_PERMISSION} from '../core/v2/continuous.ts';
import {ContinuousController,SimulatedCrash} from '../server/continuous.ts';
import {ContinuousWorker} from '../server/continuous-worker.ts';
import {validateScope} from '../server/continuous-spec.ts';
import {recordHumanResponse} from '../server/assistance-intake.ts';
import {PRIVATE_LIFE} from '../core/v2/operations.ts';
import {publicState,publicDecision} from '../core/v2/public.ts';
import {readObservation} from '../server/observation-read.ts';
import type {PlannerV2,WorkingContext} from '../core/v2/contracts.ts';
const skip=!process.env.TEST_DATABASE_URL;
const planner=(fn:(c:WorkingContext)=>Record<string,unknown>):PlannerV2=>({propose:async c=>({...await new ProductFallback().propose(c),...fn(c)})});
const worker=(h:ContinuousController,s:{id:string;planner:{identity:string}},p:PlannerV2)=>new ContinuousWorker(h,s.id,{identity:s.planner.identity,planner:p},true);
const stats=async(h:ContinuousController)=>{const x=(await h.pool.query("SELECT (SELECT count(*) FROM genesis_decisions) decisions,(SELECT count(*) FROM genesis_runtime_events) events,(SELECT count(*) FROM genesis_runtime_events WHERE status='CONSUMED') consumed,(SELECT record->>'executionLock' FROM genesis_life_state) lock,(SELECT enabled FROM genesis_schedule) schedule")).rows[0];return x;};
const op=(c:WorkingContext,operation:unknown)=>({kind:'operational',expectedRevision:c.manifest.stateRevision,sourceIds:[JSON.parse(c.text).currentEvent.id],operation});
const changes=(...ops:unknown[])=>planner(c=>({kind:'PROPOSAL',changes:ops.map(o=>op(c,o))}));
const life=async(h:ContinuousController)=>(await h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record;
const source=(c:WorkingContext)=>JSON.parse(c.text).currentEvent.id;

test('Continuous worker disabled by default; boot/API/CLI have no continuous controller import',()=>{for(const p of ['runtime/main.ts','runtime/http.ts','runtime/config.ts','scripts/run-life.mjs'])assert(!readFileSync(p,'utf8').includes('ContinuousWorker'));assert.throws(()=>eventSchema.parse({kind:'WALLET'}));});
test('Distinct SQL single-use branch preserved verbatim',()=>{const a=readFileSync('runtime/one-shot-schema.sql','utf8'),b=readFileSync('runtime/continuous-schema.sql','utf8');const start=a.indexOf(' SELECT * INTO g FROM genesis_execution_grants'),end=a.indexOf('CREATE OR REPLACE FUNCTION genesis_guard_grant_transition');assert(b.includes(a.slice(start,end).trim()));});
test('Local event to abstention to indefinite idle has no idle mutations',{skip},()=>continuousFixture(async(h,s,w)=>{
 assert.equal(await h.enqueue(manual(s),'fixture-operator'),true);const d=await w.tick();assert.equal(d.status,'COMMITTED');if(d.status==='COMMITTED'){assert.equal(d.decision.cycle,8);assert.equal(d.decision.outcome.status,'abstained');assert.equal(d.decision.biological.executedThisCycle,false);}
 const before=JSON.stringify((await h.pool.query('SELECT row_to_json(t) x FROM genesis_organisms t')).rows);for(let i=0;i<5;i++)assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal(JSON.stringify((await h.pool.query('SELECT row_to_json(t) x FROM genesis_organisms t')).rows),before);assert.deepEqual(await stats(h),{decisions:'8',events:'1',consumed:'1',lock:'CLOSED',schedule:false});
}));
test('Continuous fixture decisions 8 9 10; one event one commit across duplicate invocation',{skip},()=>continuousFixture(async(h,s,w)=>{for(let i=0;i<3;i++){await h.enqueue(manual(s,'e'+i),'fixture-operator');const r=await w.tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.cycle,8+i);}assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'10');}));
test('Dedup same ID/source never merges a changed payload; wrong organism and extra fields fail',{skip},()=>continuousFixture(async(h,s)=>{const e=manual(s);await h.enqueue(e,'fixture-operator');assert.equal(await h.enqueue(e,'fixture-operator'),false);await assert.rejects(h.enqueue({...e,payload:{...e.payload,text:'different'}},'fixture-operator'));await assert.rejects(h.enqueue({...e,id:'wrong',organismId:'other'},'fixture-operator'));await assert.rejects(h.enqueue({...e,permission:LOCAL_PERMISSION},'fixture-operator'));await assert.rejects(h.enqueue({...e,source:'cycle'},'fixture-operator'));assert.equal((await stats(h)).events,'1');}));
test('Due ordering, delayed availability, expiry and cancellation do not call planner',{skip},()=>continuousFixture(async(h,s,w)=>{const at=new Date(Date.now()-1000).toISOString();for(const id of ['b','a'])await h.enqueue({...manual(s,id),createdAt:at,availableAt:at},'fixture-operator');const f=await h.claim(s.id);assert.equal(f!.eventId,'a');await h.cancelEvent('a','fixture cancel');await h.cancelEvent('b','fixture cancel');await h.enqueue({...manual(s,'later'),availableAt:new Date(Date.now()+100000).toISOString()},'fixture-operator');await h.enqueue({...manual(s,'expired'),createdAt:at,availableAt:at,expiresAt:new Date(Date.now()-500).toISOString()},'fixture-operator');assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'7');assert.equal((await h.pool.query("SELECT status FROM genesis_runtime_events WHERE id='expired'")).rows[0].status,'EXPIRED');}));
for(const field of ['runtimeHash','constitutionHash','policyHash','permissionHash'] as const)test('Scope wrong '+field+' rejected',{skip},()=>continuousFixture(async(_h,s)=>{assert.throws(()=>validateScope({...s,[field]:'0'.repeat(64)}));}));
test('Scope cannot admit provider, external effects, OPEN permission, one-shot shape or absent evidence',{skip},()=>continuousFixture(async(h,s)=>{for(const v of [{...s,kind:'GENESIS_FIRST_AWAKENING_V1'},{...s,planner:{...s.planner,provider:'real'}},{...s,allowedEffects:['wallet']},{...s,maxConcurrent:2},{...s,forbidden:[]}])assert.throws(()=>validateScope(v));await assert.rejects(h.authorizeScope(s.id,{payloadHash:'no',issuer:s.issuer,reference:s.authorizationReference}));}));
for(const limit of ['maxCycles','maxCyclesPerWindow'] as const)test(limit+' reserves at claim and refuses later cycles',{skip},()=>continuousFixture(async(h,s,w)=>{await h.enqueue(manual(s,'one'),'fixture-operator');await h.enqueue(manual(s,'two'),'fixture-operator');assert.equal((await w.tick()).status,'COMMITTED');assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'8');},{[limit]:1}));
test('No scope or generic OPEN flag authorizes continuous execution',{skip},()=>continuousFixture(async(h,s,w)=>{const off=new ContinuousWorker(h,s.id,w.planner);assert.equal((await off.tick()).status,'DISABLED');await assert.rejects(h.claim('missing'));await h.pool.query("UPDATE genesis_life_state SET record=jsonb_set(record,'{executionLock}','\"OPEN\"')");await assert.rejects(w.tick(),/SCOPE_INVALID/);}));
test('Two workers race and stale invocation cannot commit twice',{skip},()=>continuousFixture(async(h,s,w)=>{await h.enqueue(manual(s),'fixture-operator');const r=await Promise.all([w.tick(),w.tick()]);assert.equal(r.filter(x=>x.status==='COMMITTED').length,1);assert.equal((await stats(h)).decisions,'8');assert.equal((await stats(h)).consumed,'1');}));
test('Revocation during planning refuses stale commit and survives fresh controller',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const f=(await h.claim(s.id))!,p=await h.prepare(f,{identity:s.planner.identity,planner:new ProductFallback()});await h.revoke(s.id,'operator-fixture');await assert.rejects(h.commit(f,p));await assert.rejects(new ContinuousController(h.pool).claim(s.id));assert.equal((await stats(h)).decisions,'7');assert.equal((await h.pool.query('SELECT status FROM genesis_continuous_scopes')).rows[0].status,'REVOKED');}));
test('Stale revision from independent Life State input blocks commit',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const f=(await h.claim(s.id))!,p=await h.prepare(f,{identity:s.planner.identity,planner:new ProductFallback()});await h.pool.query("UPDATE genesis_life_state SET revision=revision+1,record=jsonb_set(record,'{revision}',to_jsonb(revision+1))");await assert.rejects(h.commit(f,p));await h.fail(f,'STALE_CONTINUOUS_CLAIM',true);assert.equal((await stats(h)).decisions,'7');}));
for(const stage of ['before_claim','after_claim','before_planner','after_planner','before_policy','after_policy','before_commit','before_followup','after_followup','after_commit'])test('Crash boundary '+stage+' has atomic local recovery',{skip},()=>continuousFixture(async(original,s)=>{
 const clock=await leaseClock(original.pool);let faulted=false;const h=new ContinuousController(tailFaultPool(clock.pool,async p=>{if(p===stage&&!faulted){faulted=true;throw new SimulatedCrash(stage);}})),w=new ContinuousWorker(h,s.id,{identity:s.planner.identity,planner:new ProductFallback()},true);
 await h.enqueue(manual(s),'fixture-operator');await assert.rejects(w.tick(undefined,async p=>{if(p===stage)throw new SimulatedCrash(stage);}),SimulatedCrash);
 if(stage==='after_commit'){assert.equal((await stats(h)).decisions,'8');assert.equal(await h.recover(),0);assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');}
 else if(stage==='before_claim'){assert.equal((await stats(h)).decisions,'7');assert.equal(await h.recover(),0);const e=(await h.pool.query('SELECT status,attempts,cycle_id,lease,lease_until FROM genesis_runtime_events')).rows[0];assert.deepEqual(e,{status:'PENDING',attempts:0,cycle_id:null,lease:null,lease_until:null});assert.ok(await h.claim(s.id));assert.equal((await stats(h)).consumed,'0');return;}
 else{assert.equal((await stats(h)).decisions,'7');await clock.deadline(1);assert.equal(await h.recover(),1);await clock.advance(15);const r=await w.tick();assert.equal(r.status,'COMMITTED');assert.equal((await stats(h)).decisions,'8');}
 assert.equal((await stats(h)).consumed,'1');
},{leaseMs:250,plannerTimeoutMs:100}));
test('Repeated expired local claims use bounded backoff then fail, not infinite retry',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');await h.claim(s.id);await sleep(80);await h.recover();assert.equal(await h.claim(s.id),null);await sleep(50);await h.claim(s.id);await sleep(80);await h.recover();assert.equal((await h.pool.query('SELECT status FROM genesis_runtime_events')).rows[0].status,'FAILED');assert.equal((await stats(h)).decisions,'7');},{leaseMs:60,plannerTimeoutMs:20,backoffMs:40}));
test('Planner failure and timeout commit a failed outcome once without retry event',{skip},()=>continuousFixture(async(h,s)=>{for(const [id,p]of [['failure',{propose:async()=>{throw Error('fixture planner error');}}],['timeout',{propose:()=>new Promise<never>(()=>{})}]] as const){await h.enqueue(manual(s,id),'fixture-operator');const r=await worker(h,s,p).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.outcome.status,'failed');}assert.equal((await stats(h)).events,'2');},{plannerTimeoutMs:30}));
test('No local-effect permission and malformed operation cannot mutate Life State',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const p=planner(()=>({kind:'PROPOSAL',tool:'local_artifact',arguments:{text:'private'}}));const r=await worker(h,s,p).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.outcome.status,'denied');assert.equal((await stats(h)).decisions,'8');},{allowedEffects:[]}));
test('Provider ambiguity retains liability and stops without replay across a day boundary',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const f=(await h.claim(s.id))!;await h.pool.query("INSERT INTO genesis_provider_attempts(id,cycle_id,grant_id,at,record) VALUES('unknown',$1,'fixture',now()-interval '2 days',$2)",[f.cycleId,{status:'unknown',reservedMicros:1000,costMicros:null}]);await h.fail(f,'PROVIDER_AMBIGUITY',true);assert.equal((await h.pool.query('SELECT status FROM genesis_runtime_events')).rows[0].status,'AMBIGUOUS');await assert.rejects(h.claim(s.id));assert.equal((await h.pool.query('SELECT reserved_micros FROM genesis_continuous_attempts')).rows[0].reserved_micros,'1000');assert.equal((await stats(h)).decisions,'7');},{maxCostPerCycleMicros:1000,maxCostPerWindowMicros:1000}));
test('Aborted worker before claim or during planning never commits',{skip},()=>continuousFixture(async(h,s,w)=>{await h.enqueue(manual(s),'fixture-operator');const a=new AbortController();a.abort();assert.equal((await w.tick(a.signal)).status,'STOPPED');const b=new AbortController();const run=worker(h,s,{propose:async()=>{b.abort();return new Promise<never>(()=>{});}}).tick(b.signal);await run;assert.equal((await stats(h)).decisions,'7');}));

test('Task review becomes due, recalls creation, completes and returns to idle without focus wake',{skip},()=>continuousFixture(async(h,s)=>{
 const due=new Date(Date.now()+550).toISOString();await h.enqueue(manual(s),'fixture-operator');
 const p=changes({op:'project_create',id:'p',title:'Neutral local notes',summary:'Fixture project'}, {op:'task_create',id:'t',projectId:'p',description:'Review local note',dueAt:due},{op:'focus_set',mode:'task',targetId:'t',reason:'Recorded local focus'});
 const r=await worker(h,s,p).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.policy?.verdict,'ALLOW');assert.equal((await stats(h)).events,'2');assert.equal(await h.claim(s.id),null);await sleep(Math.max(0,Date.parse(due)-Date.now()+15));
 let recalled=false;const finish=planner(c=>{recalled=c.text.includes('manual:attempt:1:episode');return {kind:'PROPOSAL',changes:[op(c,{op:'task_status',id:'t',expectedVersion:1,status:'completed',reviewAt:null,evidenceIds:[source(c)],reason:'Local task complete'}),op(c,{op:'focus_set',mode:'idle',targetId:null,reason:'No pending action'})]};});
 const next=await worker(h,s,finish).tick();assert.equal(next.status,'COMMITTED');if(next.status==='COMMITTED')assert.equal(next.decision.policy?.verdict,'ALLOW');assert(recalled);assert.equal((await life(h)).operational.tasks[0].status,'completed');assert.equal((await worker(h,s,finish).tick()).status,'IDLE_OR_BUDGET_BLOCKED');
}));
test('Completed task invalidates scheduled review without creating another decision',{skip},()=>continuousFixture(async(h,s,w)=>{
 const due=new Date(Date.now()+450).toISOString();await h.enqueue(manual(s),'fixture-operator');await worker(h,s,changes({op:'task_create',id:'t',projectId:null,description:'Local note',dueAt:due})).tick();
 await h.enqueue(manual(s,'finish'),'fixture-operator');await worker(h,s,planner(c=>({kind:'PROPOSAL',changes:[op(c,{op:'task_status',id:'t',expectedVersion:1,status:'completed',reviewAt:null,evidenceIds:[source(c)],reason:'Already complete'})]}))).tick();
 await sleep(Math.max(0,Date.parse(due)-Date.now()+15));assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'9');assert.equal((await h.pool.query("SELECT status FROM genesis_runtime_events WHERE payload->'payload'->>'kind'='TASK_REVIEW_DUE'")).rows[0].status,'CANCELLED');
}));
test('Database artifacts v1 and v2 continue across fresh controller with bounded historical recall',{skip},()=>continuousFixture(async(h,s,_w,schema,url)=>{
 await h.enqueue(manual(s),'fixture-operator');const r=await worker(h,s,changes({op:'project_create',id:'p',title:'Local notes',summary:'Neutral project'},{op:'task_create',id:'t',projectId:'p',description:'Maintain local notes',dueAt:null},{op:'artifact_create',id:'a',projectId:'p',taskId:'t',content:'PRIVATE_ARTIFACT_VERSION_ONE'})).tick();assert.equal(r.status,'COMMITTED');
 const pool=new pg.Pool({connectionString:url,options:`-c search_path=${schema}`});try{const fresh=new ContinuousController(pool);await fresh.enqueue(manual(s,'review',{kind:'TASK_REVIEW_DUE',targetId:'t',targetVersion:1}),'fixture-operator');let recall=false;const r2=await worker(fresh,s,planner(c=>{recall=c.text.includes('PRIVATE_ARTIFACT_VERSION_ONE');assert(Buffer.byteLength(c.text)<=12000);return {kind:'PROPOSAL',changes:[op(c,{op:'artifact_revise',id:'a',expectedVersion:1,content:'PRIVATE_ARTIFACT_VERSION_TWO',reason:'Local revision'})]};})).tick();assert.equal(r2.status,'COMMITTED');assert(recall);const versions=(await life(fresh)).operational.artifacts[0].versions;assert.deepEqual(versions.map((x:{content:string})=>x.content),['PRIVATE_ARTIFACT_VERSION_ONE','PRIVATE_ARTIFACT_VERSION_TWO']);}finally{await pool.end();}
}));
test('DEFER persists exactly one future wake; repeated deferral reaches policy chain limit',{skip},()=>continuousFixture(async(h,s)=>{
 await h.enqueue(manual(s),'fixture-operator');const p=planner(()=>({kind:'DEFER',deferUntil:new Date(Date.now()+120).toISOString()})),w=worker(h,s,p);
 for(let i=0;i<3;i++){const r=await w.tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.outcome.status,i===2?'denied':'deferred');if(i<2){assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');await sleep(150);}}
 assert.equal((await stats(h)).events,'3');assert.equal((await stats(h)).consumed,'3');assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');
},{maxDepth:2}));
test('Immediate continuation reaches declared depth and root-rate guards, never infinite work',{skip},()=>continuousFixture(async(h,s)=>{
 await h.enqueue(manual(s),'fixture-operator');const p=planner(()=>({kind:'PROPOSAL',followUp:{kind:'CONTINUATION',availableAt:new Date().toISOString(),reason:'Local next part'}})),w=worker(h,s,p);
 for(let i=0;i<3;i++){const r=await w.tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.policy?.verdict,i===2?'DENY':'ALLOW');}assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'10');
},{maxDepth:2}));
test('Root immediate-rate ceiling terminates next event before planning',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const w=worker(h,s,planner(()=>({kind:'PROPOSAL',followUp:{kind:'CONTINUATION',availableAt:new Date().toISOString(),reason:'Next local part'}})));await w.tick();assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'8');assert.equal((await h.pool.query("SELECT reason FROM genesis_runtime_events WHERE status='FAILED'")).rows[0].reason,'ROOT_RATE_LIMIT');},{maxImmediatePerRoot:1,backoffMs:10000}));
test('Typed wake permission cannot be replaced by prose, wrong target or disabled scheduling',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const r=await worker(h,s,planner(()=>({kind:'PROPOSAL',followUp:{kind:'PROJECT_REVIEW',targetId:'unknown',availableAt:new Date().toISOString()}}))).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.policy?.verdict,'DENY');assert.equal((await stats(h)).events,'1');},{scheduling:false}));

async function answer(h:ContinuousController,s:{organismId:string},requestId:string,id:string,wake=true){const l=await life(h);return recordHumanResponse(h.pool,{id,organismId:s.organismId,requestId,receivedAt:new Date().toISOString(),respondentRef:'private-fixture-human',attributionReference:'private-input-evidence',content:'PRIVATE_ANSWER_CANARY is untrusted input, not authority.',relationshipId:null,trust:'untrusted',disclosure:PRIVATE_LIFE},{organismId:s.organismId,expectedRevision:l.revision,operatorRef:'fixture-operator',authorizationRef:'fixture-intake',scope:'RECORD_HUMAN_RESPONSE_ONLY',...(wake?{wake:'ENQUEUE_IF_INSTALLED'}:{})});}
test('Human waiting creates no poll cycles; attributed answer creates one wake and resolves via policy',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');const req=await worker(h,s,planner(()=>({kind:'REQUEST_ASSISTANCE',assistance:'Which local record is current?'}))).tick();assert.equal(req.status,'COMMITTED');assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');const id=(await life(h)).operational.assistance[0].id;let view=await readObservation(h.pool);assert.equal(publicState(view.organism,view.life,view.facts).status,'AWAITING_ASSISTANCE');
 await answer(h,s,id,'response');await assert.rejects(answer(h,s,id,'response'));assert.equal((await stats(h)).events,'2');let seen=false;
 const done=await worker(h,s,planner(c=>{seen=c.text.includes('PRIVATE_ANSWER_CANARY')&&c.text.includes('manual:attempt:1:episode');const q=JSON.parse(c.text).operationalLife.items.find((x:{id:string})=>x.id===id);return {kind:'PROPOSAL',changes:[op(c,{op:'assistance_resolve',id,expectedVersion:q.version,responseId:'response',reason:'Recorded response reviewed'})]};})).tick();assert.equal(done.status,'COMMITTED');if(done.status==='COMMITTED')assert.equal(done.decision.policy?.verdict,'ALLOW');assert(seen);assert.equal((await life(h)).operational.assistance[0].status,'resolved');view=await readObservation(h.pool);const pub=JSON.stringify({...publicState(view.organism,view.life,view.facts),history:view.history.map(publicDecision)});assert(!pub.includes('PRIVATE_ANSWER_CANARY'));assert(!pub.includes('private-fixture-human'));assert(!pub.includes('fixture-intake'));
}));
test('Distinct human answers keep distinct wake identities; revocation prevents response wake execution',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await worker(h,s,planner(()=>({kind:'REQUEST_ASSISTANCE',assistance:'Which local record?'}))).tick();const id=(await life(h)).operational.assistance[0].id;await answer(h,s,id,'response1');await answer(h,s,id,'response2');assert.equal((await stats(h)).events,'3');await h.revoke(s.id,'fixture stop');await assert.rejects(w.tick());assert.equal((await stats(h)).decisions,'8');assert.equal((await h.pool.query("SELECT count(*) n FROM genesis_runtime_events WHERE status='PENDING'")).rows[0].n,'2');
}));
test('Cancelled assistance response event is discarded before planner and future intake rejected',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await worker(h,s,planner(()=>({kind:'REQUEST_ASSISTANCE',assistance:'Which record?'}))).tick();const id=(await life(h)).operational.assistance[0].id;
 // Cancellation first, then a later answer cannot be ingested against a closed request.
 await h.enqueue(manual(s,'cancel'),'fixture-operator');await worker(h,s,changes({op:'assistance_cancel',id,expectedVersion:1,reason:'No answer required'})).tick();await assert.rejects(answer(h,s,id,'late-answer'));assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).events,'2');
}));
test('Read-only public projection distinguishes active, idle and stale review; private event never disclosed',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s,'private',{kind:'MANUAL_EVENT',text:'PRIVATE_EVENT_CANARY',references:[]}),'fixture-operator');const f=(await h.claim(s.id))!;let v=await readObservation(h.pool);assert.equal(publicState(v.organism,v.life,v.facts).status,'REASONING');assert(!JSON.stringify(publicState(v.organism,v.life,v.facts)).includes('PRIVATE_EVENT_CANARY'));await h.commit(f,await h.prepare(f,w.planner));v=await readObservation(h.pool);assert.equal(publicState(v.organism,v.life,v.facts).status,'IDLE');assert(!JSON.stringify(v.history.map(publicDecision)).includes('PRIVATE_EVENT_CANARY'));
 await h.enqueue(manual(s,'stale'),'fixture-operator');await h.claim(s.id);await sleep(270);v=await readObservation(h.pool);assert.equal(publicState(v.organism,v.life,v.facts).status,'REVIEW_REQUIRED');
},{leaseMs:250,plannerTimeoutMs:100}));
test('Expired scope cannot claim and immutable scope/event payload guards reject replacement',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await assert.rejects(h.pool.query("UPDATE genesis_continuous_scopes SET payload=jsonb_set(payload,'{maxCycles}','9999')"));await assert.rejects(h.pool.query("UPDATE genesis_runtime_events SET payload=jsonb_set(payload,'{depth}','2')"));await sleep(Math.max(0,Date.parse(s.expiresAt)-Date.now()+20));await assert.rejects(w.tick());assert.equal((await stats(h)).decisions,'7');
},{expiresAt:new Date(Date.now()+600).toISOString()}));
test('Unresolved earlier-day provider liability and exhausted recorded costs prevent new claims',{skip},()=>continuousFixture(async(h,s)=>{
 await h.enqueue(manual(s),'fixture-operator');await h.pool.query("INSERT INTO genesis_provider_attempts(id,cycle_id,grant_id,at,record) VALUES('old','unrelated','fixture',now()-interval '2 days',$1)",[{status:'unknown',reservedMicros:10,costMicros:null}]);assert.equal(await h.claim(s.id),null);const r=await h.tx(c=>h.resources(c,s));assert.equal(r.reservedMicros,10);assert.equal(r.unresolvedProviderAttempts,1);
}));
test('Single-use controller still permits only Decision 8 after new schema; distinct scope cannot be substituted',{skip},()=>oneShotFixture(async(h,g)=>{
 const c=new ContinuousController(h.pool);await c.installFixtureSchema();await authorize(h,g);await assert.rejects(c.claim(g.id));const f=await h.claim(g.id),p=await h.prepare(f,{identity:g.planner.identity,planner:new ProductFallback()});await h.commit(f,p);await assert.rejects(h.claim(g.id));await assert.rejects(c.claim(g.id));assert.equal((await stats(c)).decisions,'8');assert.equal((await stats(c)).lock,'CLOSED');
}));
test('Disabled run and graceful polling shutdown never call planner when queue is empty',{skip},()=>continuousFixture(async(h,s)=>{let calls=0;const p={identity:s.planner.identity,planner:{propose:async()=>{calls++;throw Error('Should not run');}}};await new ContinuousWorker(h,s.id,p).run(new AbortController().signal);const a=new AbortController(),w=new ContinuousWorker(h,s.id,p,true,25);let ticks=0;await w.run(a.signal,()=>{if(++ticks===3)a.abort();});assert.equal(calls,0);assert.equal((await stats(h)).decisions,'7');}));

for(const phase of ['after_claim','before_followup','after_followup','after_commit'])test('Fresh-process exit '+phase+' preserves real follow-up atomicity',{skip},()=>continuousFixture(async(h,s,_w,schema,url)=>{
 await h.enqueue(manual(s),'fixture-operator');const child=spawn(process.execPath,['tests/support/continuous-crash.ts',phase],{cwd:process.cwd(),env:{PATH:process.env.PATH,NODE_ENV:'test',TEST_DATABASE_URL:url,FIXTURE_SCHEMA:schema},stdio:['ignore','pipe','pipe']});let err='';child.stderr.on('data',x=>err+=x);const code=await new Promise<number|null>(r=>child.on('exit',r));assert.equal(code,77,err);
 const expected=phase==='after_commit'?8:7;assert.equal((await stats(h)).decisions,String(expected));assert.equal((await stats(h)).events,phase==='after_commit'?'2':'1');
 if(phase!=='after_commit'){await sleep(600);await h.recover();await sleep(15);const r=await worker(new ContinuousController(h.pool),s,planner(()=>({kind:'PROPOSAL',followUp:{kind:'CONTINUATION',availableAt:new Date(Date.now()+60000).toISOString(),reason:'Later local review'}}))).tick();assert.equal(r.status,'COMMITTED');}
 assert.equal((await stats(h)).decisions,'8');assert.equal((await stats(h)).events,'2');assert.equal((await stats(h)).consumed,'1');assert.equal(await h.recover(),0);
},{leaseMs:550,plannerTimeoutMs:200}));

test('100-cycle deterministic local life remains bounded, recalls earlier work and stops at scope budget',{skip},async()=>{const {longRun}=await import('./support/continuous-long-run.ts');const {writeFileSync}=await import('node:fs');const result=await longRun();writeFileSync('outputs/continuous-life-pass/long-run.json',JSON.stringify(result,null,2)+'\n');});
test('Assistance persistence requires the life_changes effect class',{skip},()=>continuousFixture(async(h,s)=>{await h.enqueue(manual(s),'fixture-operator');const r=await worker(h,s,planner(()=>({kind:'REQUEST_ASSISTANCE',assistance:'Which note?'}))).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.policy?.verdict,'DENY');assert.equal((await life(h)).operational?.assistance.length??0,0);},{allowedEffects:[]}));

test('Commitment creation with review time creates a due wake; completion cancels it before reasoning',{skip},()=>continuousFixture(async(h,s,w)=>{
 const due=new Date(Date.now()+400).toISOString();await h.enqueue(manual(s),'fixture-operator');const r=await worker(h,s,changes({op:'commitment_create',id:'k',projectId:null,taskId:null,relationshipId:null,purpose:'maintain_local_constraint',statement:'Review local note',reviewAt:due})).tick();assert.equal(r.status,'COMMITTED');assert.equal((await stats(h)).events,'2');
 await h.enqueue(manual(s,'cancel'),'fixture-operator');const r2=await worker(h,s,changes({op:'commitment_status',id:'k',expectedVersion:1,status:'cancelled',reviewAt:null,evidenceIds:[],reason:'No longer required'})).tick();assert.equal(r2.status,'COMMITTED');await sleep(Math.max(0,Date.parse(due)-Date.now()+10));assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await stats(h)).decisions,'9');
}));
test('Task deferral LifeChange creates one version-bound wake, separate from proposal DEFER',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await worker(h,s,changes({op:'task_create',id:'t',projectId:null,description:'Local note',dueAt:null})).tick();await h.enqueue(manual(s,'defer'),'fixture-operator');const due=new Date(Date.now()+250).toISOString();const r=await worker(h,s,changes({op:'task_status',id:'t',expectedVersion:1,status:'deferred',reviewAt:due,evidenceIds:[],reason:'Later review'})).tick();assert.equal(r.status,'COMMITTED');assert.equal((await stats(h)).events,'3');assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');await sleep(270);assert.equal((await w.tick()).status,'COMMITTED');assert.equal((await stats(h)).decisions,'10');
}));
test('Project abandonment and question resolution discard stale reviews without a decision',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await worker(h,s,changes({op:'project_create',id:'p',title:'Local notes',summary:'Private project'},{op:'question_create',id:'q',question:'Which note?',projectId:'p',taskId:null})).tick();const due=new Date(Date.now()+400).toISOString();for(const [id,kind] of [['p','PROJECT_REVIEW'],['q','QUESTION_REVIEW']] as const)await h.enqueue({...manual(s,'review-'+id,{kind,targetId:id,targetVersion:1}),availableAt:due},'fixture-operator');
 await h.enqueue(manual(s,'finish'),'fixture-operator');const r=await worker(h,s,planner(c=>({kind:'PROPOSAL',changes:[op(c,{op:'project_status',id:'p',expectedVersion:1,status:'abandoned',reason:'End local work'}),op(c,{op:'question_status',id:'q',expectedVersion:1,status:'resolved',evidenceIds:[source(c)],reason:'Recorded answer'})]}))).tick();assert.equal(r.status,'COMMITTED');await sleep(Math.max(0,Date.parse(due)-Date.now()+10));assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await h.pool.query("SELECT count(*) n FROM genesis_runtime_events WHERE status='CANCELLED'")).rows[0].n,'2');assert.equal((await stats(h)).decisions,'9');
}));
test('An answer queued before cancellation is discarded, rather than waking a cancelled request',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await worker(h,s,planner(()=>({kind:'REQUEST_ASSISTANCE',assistance:'Which note?'}))).tick();const id=(await life(h)).operational.assistance[0].id;await h.enqueue(manual(s,'cancel'),'fixture-operator');await answer(h,s,id,'response');const r=await worker(h,s,changes({op:'assistance_cancel',id,expectedVersion:2,reason:'No longer needed'})).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.policy?.verdict,'ALLOW');assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await h.pool.query("SELECT status FROM genesis_runtime_events WHERE payload->'payload'->>'kind'='HUMAN_RESPONSE_RECEIVED'")).rows[0].status,'CANCELLED');
}));
test('Recorded costs beyond window ceiling block dispatch; local planner cannot charge or change identity',{skip},()=>continuousFixture(async(h,s,w)=>{
 await h.enqueue(manual(s),'fixture-operator');await h.pool.query("INSERT INTO genesis_provider_attempts(id,cycle_id,grant_id,at,record) VALUES('spent','prior','fixture',now(),$1)",[{status:'completed',reservedMicros:0,costMicros:1}]);assert.equal((await w.tick()).status,'IDLE_OR_BUDGET_BLOCKED');assert.equal((await h.tx(c=>h.resources(c,s))).committedMicros,1);assert.equal((await stats(h)).decisions,'7');
}));
test('Nonzero local planner charge becomes one failed outcome; unknown planner identity refuses processing',{skip},()=>continuousFixture(async(h,s)=>{
 await h.enqueue(manual(s),'fixture-operator');const f=(await h.claim(s.id))!;await assert.rejects(h.prepare(f,{identity:'unadmitted',planner:new ProductFallback()}));await h.cancelEvent(f.eventId!,'operator');await h.enqueue(manual(s,'charged'),'fixture-operator');const r=await worker(h,s,planner(()=>({cost:{namespace:'OPERATIONAL',maxMicros:1}}))).tick();assert.equal(r.status,'COMMITTED');if(r.status==='COMMITTED')assert.equal(r.decision.outcome.status,'failed');assert.equal((await h.tx(c=>h.resources(c,s))).failures,1);
}));
test('Non-fixture scope requires reviewed prior awakening; queue cannot alter permissions or cross scopes',{skip},()=>continuousFixture(async(h,s)=>{
 assert.throws(()=>validateScope({...s,organismId:'817e772c-827e-48fc-8e35-6504cb2a8d2d',minimumPriorDecisions:7}));await h.enqueue(manual(s),'fixture-operator');const f=(await h.claim(s.id))!;await assert.rejects(h.prepare({...f,continuousScopeId:'other'},{identity:s.planner.identity,planner:new ProductFallback()}));await assert.rejects(h.prepare({...f,oneShotGrantId:'fake'},{identity:s.planner.identity,planner:new ProductFallback()}));await h.cancelEvent(f.eventId!,'fixture');
}));

test('Phase-persistence database failure after policy cannot commit a previously allowed effect',{skip},()=>continuousFixture(async(h,s)=>{
 await h.enqueue(manual(s),'fixture-operator');const query=h.pool.query;let injected=false;
 Object.defineProperty(h.pool,'query',{configurable:true,value:function(...args:unknown[]){if(typeof args[0]==='string'&&args[0].startsWith('UPDATE genesis_continuous_attempts SET phase')&&Array.isArray(args[1])&&args[1][1]==='after_policy'){injected=true;return Promise.reject(new Error('FIXTURE_DATABASE_PHASE_FAILURE'));}return Reflect.apply(query,h.pool,args);}});
 try{const r=await worker(h,s,changes({op:'project_create',id:'p',title:'Local note',summary:'Must not commit after DB failure'})).tick();assert.equal(r.status,'CLOSED_WITH_ERROR');assert(injected);assert.equal((await stats(h)).decisions,'7');assert.equal((await life(h)).operational?.projects.length??0,0);assert.equal((await h.pool.query('SELECT status FROM genesis_runtime_events')).rows[0].status,'FAILED');}finally{Object.defineProperty(h.pool,'query',{configurable:true,value:query});}
}));
