import test from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {createHash,randomUUID} from 'node:crypto';
import {deploymentFixture} from './support/deployment-fixture.ts';import {planInstall,applyInstall} from '../runtime/deployment/install.ts';
import {consumeExisting} from '../runtime/deployment/consumer.ts';import {runtimeIdentity,makeGrant} from '../server/one-shot-spec.ts';
import {OperatorAuthentication,CAPABILITIES} from '../server/operator-auth.ts';import {OperatorControl,type OperatorCommand} from '../server/operator-control.ts';
import {fixtureAdmission,TEST_SECRET} from './support/reasoning-fixture.ts';import {CLOSED_PERMISSIONS,digest} from '../core/v2/identity.ts';
import {readMemoryArchive} from '../server/memory-store.ts';import {disclosureSources} from '../server/disclosure-store.ts';
import {continuousIdentity,FORBIDDEN} from '../server/continuous-spec.ts';import {EVENT_KINDS,LOCAL_PERMISSION} from '../core/v2/continuous.ts';
import {ContinuousController} from '../server/continuous.ts';import {restoreFixture} from './support/deployment-restore.ts';
import {inspectReadiness} from '../runtime/deployment/readiness.ts';import {observationServer,stopObservation} from '../runtime/deployment/http-server.ts';import {GenesisService} from '../runtime/service.ts';import {LifeStore} from '../server/store.ts';

test('deployment topology: owner install, separate operator/worker, mock Decision8, restart, local scope, revoke, restore',async()=>deploymentFixture(async(owner,url,schema,roles)=>{
 const o=(await owner.query('SELECT state,revision FROM genesis_organisms')).rows[0],life=(await owner.query('SELECT record,revision FROM genesis_life_state')).rows[0];
 const plan=await planInstall(owner,url,o.state.id,o.state.bornAt,roles);await applyInstall(owner,url,plan,'INSTALL_REVIEWED_PLAN:'+plan.hash);
 // Provisioning an authenticated fixture actor belongs exclusively to migration owner.
 await owner.query('INSERT INTO genesis_operator_actors(id,enabled,capabilities) VALUES($1,true,$2)',['operator-a',CAPABILITIES]);
 const auth=new OperatorAuthentication({enabled:true,mode:'test',keys:[{id:'fixture',actorId:'operator-a',sha256:createHash('sha256').update(TEST_SECRET).digest('hex'),expiresAt:'2099-01-01T00:00:00.000Z'}]});const principal=auth.authenticate(TEST_SECRET);
 let opPool=new pg.Pool({connectionString:url,options:`-c search_path=${schema} -c role=${roles.operator}`}),worker=new pg.Pool({connectionString:url,options:`-c search_path=${schema} -c role=${roles.worker}`});
 let control=new OperatorControl(opPool,auth);
 const call=(operation:OperatorCommand['operation'],v:Partial<OperatorCommand>={})=>control.execute(principal,{id:'test:'+randomUUID(),organismId:o.state.id,operation,targetId:null,expectedHash:null,reasonReference:'review:fixture-provider',payload:null,...v});
 const rowHash=async(table:string,id:string)=>digest(JSON.parse(JSON.stringify((await owner.query(`SELECT * FROM ${table} WHERE id=$1`,[id])).rows[0])));
 try{
 const sources=disclosureSources(o.state,life.record,await readMemoryArchive(owner,o.state.id,Number(life.revision)));const project=sources.find(s=>s.type==='legacy_project_metadata');assert.ok(project,'fixture project required');
 await call('review_disclosure',{targetId:project.id,payload:{sourceType:project.type,sourceId:project.id,sourceHash:project.hash,audience:'PROVIDER_DISCLOSURE',decision:'APPROVED',expectedVersion:0,expiresAt:null}});
 const a=fixtureAdmission();await call('propose_provider',{targetId:a.id,payload:a});await call('admit_provider',{targetId:a.id,expectedHash:await rowHash('genesis_provider_admissions',a.id)});
 const g=makeGrant({id:'deployment-one-shot',organismId:o.state.id,stateRevision:Number(o.revision),lifeRevision:Number(life.revision),issuer:'operator-a',authorizationReference:a.reviewReference,permission:{...CLOSED_PERMISSIONS,execution:true,localArtifacts:true,llm:true,maxAttempts:1,maxCostMicros:50000},planner:{identity:'provider:fixture:fixture-model',provider:'fixture',model:a.model,admissionHash:digest(a)},at:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+600000).toISOString()});
 await call('propose_grant',{targetId:g.id,payload:g});await call('authorize_grant',{targetId:g.id,expectedHash:await rowHash('genesis_execution_grants',g.id)});
 const req={version:1,id:'launch:'+randomUUID(),mode:'one-shot',organismId:o.state.id,bornAt:o.state.bornAt,runtimeHash:runtimeIdentity().sha256,targetId:g.id,authorityRowHash:await rowHash('genesis_execution_grants',g.id),admissionId:a.id,reviewReference:a.reviewReference,maximumSessionMs:30000};let sends=0;
 const d=await consumeExisting(req,opPool,worker,auth,principal,new AbortController().signal,{secretResolver:{resolve:async()=>TEST_SECRET},fixtureScenario:'abstain',onFixtureSend:()=>sends++});assert.equal(d.cycle,8);assert.equal(sends,1);
 await opPool.end();await worker.end();opPool=new pg.Pool({connectionString:url,options:`-c search_path=${schema} -c role=${roles.operator}`});worker=new pg.Pool({connectionString:url,options:`-c search_path=${schema} -c role=${roles.worker}`});control=new OperatorControl(opPool,auth);
 await assert.rejects(consumeExisting(req,opPool,worker,auth,principal,new AbortController().signal));assert.equal((await owner.query('SELECT count(*) n FROM genesis_decisions')).rows[0].n,'8');assert.equal((await owner.query('SELECT status FROM genesis_execution_grants')).rows[0].status,'CONSUMED');assert.equal((await owner.query('SELECT count(*) n FROM genesis_provider_receipts')).rows[0].n,'1');assert.equal((await owner.query('SELECT count(*) n FROM genesis_continuous_scopes')).rows[0].n,'0');
 assert.equal((await inspectReadiness(opPool,{organismId:o.state.id,bornAt:o.state.bornAt})).ready,true);
 const reader=new pg.Pool({connectionString:url,options:`-c search_path=${schema} -c role=${roles.reader}`});const server=observationServer(new GenesisService(new LifeStore(reader),{databaseUrl:'fixture',operatorToken:'unused',host:'127.0.0.1',port:3001,intervalMs:30000,maxDailyCycles:1,autonomous:false,internet:false,startingCents:0,plannerMode:'local',allowedOrigins:[]}),reader,{organismId:o.state.id,bornAt:o.state.bornAt});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));try{const res=await fetch('http://127.0.0.1:'+(server.address() as {port:number}).port+'/api/state');assert.equal(res.status,200);assert.ok(!(await res.text()).includes(TEST_SECRET));}finally{await stopObservation(server,reader);}
 // Separate authority. Mock provider remains one-shot only; local worker can abstain.
 const s={version:1,kind:'CONTINUOUS_LOCAL_V1',id:'deployment-local-scope',organismId:o.state.id,...continuousIdentity(),biologicalMode:'SAVED-OBSERVATION-ONLY',planner:{kind:'LOCAL_DETERMINISTIC',identity:'product-deterministic-v1',provider:null,model:null},allowedEvents:[...EVENT_KINDS],allowedEffects:['local_reflection','local_artifact','life_changes'],forbidden:[...FORBIDDEN],scheduling:true,permissionHash:digest(LOCAL_PERMISSION),minimumPriorDecisions:8,maxCycles:2,windowMs:1000,maxCyclesPerWindow:2,maxConcurrent:1,maxCostPerCycleMicros:0,maxCostPerWindowMicros:0,leaseMs:10000,plannerTimeoutMs:1000,maxAttemptsPerEvent:1,backoffMs:100,maxDepth:1,maxFollowups:1,maxImmediatePerRoot:2,minimumDelayMs:100,issuedAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+600000).toISOString(),issuer:'operator-a',authorizationReference:a.reviewReference};
 await call('propose_scope',{targetId:s.id,payload:s});await call('authorize_scope',{targetId:s.id,expectedHash:await rowHash('genesis_continuous_scopes',s.id)});
 await new Promise(r=>setTimeout(r,1100));const at=new Date(Date.now()-100).toISOString();await new ContinuousController(opPool).enqueue({version:1,id:'fixture-local-event',organismId:o.state.id,createdAt:at,availableAt:at,expiresAt:null,dedupKey:'fixture-local-event',source:'operator',sourceRef:'fixture-operator',visibility:'private',disclosure:{internal:true,provider:false,public:false},parentEventId:null,parentCycleId:null,rootId:'fixture-local-event',depth:0,payload:{kind:'MANUAL_EVENT',text:'Neutral fixture event',references:[]}},'fixture-operator');
 const local={...req,id:'launch:'+randomUUID(),mode:'continuous-local',targetId:s.id,authorityRowHash:await rowHash('genesis_continuous_scopes',s.id),admissionId:null,maximumSessionMs:3500};await consumeExisting(local,opPool,worker,auth,principal,new AbortController().signal);assert.equal((await owner.query('SELECT count(*) n FROM genesis_decisions')).rows[0].n,'9',JSON.stringify((await owner.query('SELECT status,reason FROM genesis_runtime_events')).rows));
 await call('revoke_scope',{targetId:s.id,expectedHash:await rowHash('genesis_continuous_scopes',s.id)});await assert.rejects(consumeExisting({...local,id:'launch:'+randomUUID()},opPool,worker,auth,principal,new AbortController().signal));
 const restored=await restoreFixture(owner,url,schema);assert.equal(restored.decisions,9);assert.equal(restored.attempts,1);assert.equal(restored.receipts,1);
 assert.equal((await owner.query('SELECT record FROM genesis_life_state')).rows[0].record.executionLock,'CLOSED');assert.equal((await owner.query('SELECT enabled FROM genesis_schedule')).rows[0].enabled,false);assert.equal(sends,1);
 }finally{await opPool.end();await worker.end();}
}));
