import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import pg from 'pg';
import {initialLifeState,CLOSED_PERMISSIONS,digest} from '../core/v2/identity.ts';
import {SavedObservationAdapter} from '../core/v2/biology.ts';
import {compileContext} from '../core/v2/context.ts';
import {retrieveMemory,EMPTY_QUERY,MEMORY_LIMITS,RECALL_POLICY,utf8Excerpt,type MemoryArchive,type MemoryReview,type MemoryQuery} from '../core/v2/memory.ts';
import {loadMemoryArchive,readMemoryArchive} from '../server/memory-store.ts';
import {ProductFallback} from '../core/v2/planner.ts';
import {publicState,publicDecision} from '../core/v2/public.ts';
import {activeFixture} from './support/active-fixture.ts';
import {oneShotFixture,authorize} from './support/one-shot-fixture.ts';
import type {Organism} from '../core/contracts.ts';
import type {MemoryAssertion} from '../core/v2/contracts.ts';
const now='2026-09-20T12:00:00.000Z',at='2026-09-19T12:00:00.000Z';
const skip=!process.env.TEST_DATABASE_URL;
function fixture(){const o=JSON.parse(readFileSync('tests/fixtures/genesis-dormant-sanitized.json','utf8')) as Organism;const life=initialLifeState(o,0);const bio=new SavedObservationAdapter(o.id,()=>now).accept({id:'current',kind:'digital-event',source:'fixture',observedAt:now});const archive:MemoryArchive={legacy:[],decisions:[],episodes:[],complete:true};return {o,life,bio,archive};}
function episode(f:ReturnType<typeof fixture>,n=1,options:{text?:string;project?:string;task?:string;at?:string;recall?:unknown}={}){
 const time=options.at??at,key='d'+n,ep=key+':episode';
 const d={schemaVersion:2,id:key,organismId:f.o.id,cycle:7+n,at:time,event:{id:key+':event',kind:'digital-event',source:'fixture',observedAt:time},biological:{id:key+':bio',observedAt:time,status:'not_applied',executedThisCycle:false},outcome:{status:options.text?'local':'abstained'},action:{status:options.text?'local_saved':'not_executed',...(options.text?{artifact:options.text}:{})},proposal:{projectId:options.project??null,taskId:options.task??null},memory:{episode:{id:ep},changes:[]},reasoning:{rationale:'HIDDEN_REASONING_CANARY'},providerResponse:'PROVIDER_RESPONSE_CANARY'};
 const e={schemaVersion:1,id:ep,organismId:f.o.id,at:time,kind:'episode',source:key,visibility:'private',record:{recall:options.recall===undefined?RECALL_POLICY:options.recall,outcomeStatus:d.outcome.status,actionStatus:d.action.status,...(options.text?{localArtifact:options.text}:{}),providerError:'RAW_ERROR_CANARY'}};
 f.archive.decisions.push(d);f.archive.episodes.push(e);return {d,e};
}
function select(f:ReturnType<typeof fixture>,q:Partial<MemoryQuery>={},audience:'internal'|'provider'='internal',reviews:MemoryReview[]=[],limits=MEMORY_LIMITS){return retrieveMemory(f.o,f.life,f.bio,f.archive,{...EMPTY_QUERY,...q},audience,limits,reviews);}
function assertion(f:ReturnType<typeof fixture>,id:string,sources:string[],other:Partial<MemoryAssertion>={}){const a:MemoryAssertion={id,text:'Remembered unverified statement',sources,confidence:0.4,author:'planner',verified:false,supersedes:null,contradictions:[],...other};f.life.semanticMemory.push(a);return a;}
function legacy(f:ReturnType<typeof fixture>){const m={id:'legacy1',at,text:'A past computational experience',sourceDecision:'old1',salience:0.9};f.archive.legacy.push(m);f.archive.decisions.push({id:'old1',at,cycle:1});return m;}
function review(f:ReturnType<typeof fixture>,raw:{id:string},other:Partial<MemoryReview>={}):MemoryReview{return {id:raw.id,organismId:f.o.id,sourceHash:digest(raw),reference:'fixture-reviewed-disclosure',internal:true,provider:false,public:false,operatorOnly:false,...other};}

test('Legacy conversion fails closed without disclosure and retains original source after explicit internal review',()=>{const f=fixture(),m=legacy(f),original=digest(m);assert.equal(select(f).items.length,0);assert.match(select(f).manifest.excluded[0].reason,/not admitted/);const s=select(f,{},'internal',[review(f,m)]);assert.equal(s.items[0].kind,'legacy_episode');assert.equal(s.items[0].occurredAt,at);assert.deepEqual(s.items[0].sourceIds,['legacy1','old1']);assert.equal(s.items[0].provenance[0].hash,original);assert.equal(digest(m),original);assert.match(s.items[0].limitations[0],/not biological/);});
test('Internal provider public and operator-only disclosure are independent',()=>{const f=fixture(),m=legacy(f);assert.equal(select(f,{},'provider',[review(f,m,{public:true})]).items.length,0);assert.equal(select(f,{},'internal',[review(f,m,{operatorOnly:true,provider:true})]).items.length,0);const s=select(f,{},'provider',[review(f,m,{provider:true})]);assert.equal(s.items.length,1);assert.equal(s.items[0].disclosure.public,false);});
test('Stale disclosure cannot be reused for changed content or another organism',()=>{const f=fixture(),m=legacy(f),r=review(f,m);m.text='changed';assert.equal(select(f,{},'internal',[r]).items.length,0);assert.throws(()=>select(f,{},'internal',[{...r,organismId:'wrong'}]));});
test('V2 conversion exports structured outcomes not planner reasoning or error bodies',()=>{const f=fixture();episode(f);const s=select(f);assert.equal(s.items.length,1);assert.equal(s.items[0].kind,'episode');assert.match(s.items[0].excerpt,/abstained/);for(const value of ['HIDDEN_REASONING_CANARY','PROVIDER_RESPONSE_CANARY','RAW_ERROR_CANARY'])assert(!JSON.stringify(s).includes(value));assert.equal(s.items[0].interpretation,'recorded_past_experience');});
test('Historical private episodes without versioned internal-use policy remain excluded',()=>{const f=fixture();episode(f,1,{recall:null});assert.equal(select(f).items.length,0);assert.match(select(f).manifest.excluded[0].reason,/missing-disclosure/);});
test('Future private episode is internally usable but not automatically provider-disclosed',()=>{const f=fixture();episode(f);assert.equal(select(f).items.length,1);assert.equal(select(f,{},'provider').items.length,0);});
test('Artifact identity association and bounded UTF8 excerpt retain producing episode',()=>{const f=fixture();const {e}=episode(f,1,{text:'Note about orchard work 🍃'.repeat(200),project:'p',task:'t'});const s=select(f,{taskIds:['t']});const a=s.items.find(i=>i.kind==='artifact')!;assert.equal(a.id,e.id+':artifact');assert(a.sourceIds.includes(e.id));assert.deepEqual(a.projectIds,['p']);assert.deepEqual(a.taskIds,['t']);assert(Buffer.byteLength(a.excerpt)<=600);assert(!a.excerpt.includes('\uFFFD'));assert(!JSON.stringify(s).includes('RAW_ERROR_CANARY'));});
test('Corrupted artifact cannot be recalled',()=>{const f=fixture();const {d}=episode(f,1,{text:'good'});d.action.artifact='different';assert(!select(f).items.some(i=>i.kind==='artifact'));assert(select(f).manifest.excluded.some(e=>e.reason==='corrupted artifact reference'));});
test('Semantic source resolves a past event without selecting its episode text',()=>{const f=fixture();const {d}=episode(f);assertion(f,'belief',[d.event.id]);const s=select(f,{},'internal',[],{...MEMORY_LIMITS,episodes:0});assert.equal(s.items.length,1);assert.equal(s.items[0].kind,'assertion');assert.equal(s.items[0].confidence,0.4);assert.equal(s.items[0].occurredAt,null);assert.equal(s.items[0].provenance[0].recordId,d.id);assert.equal(s.items[0].interpretation,'unverified_assertion');});
test('Biological source resolves only as provenance, never neural memory converted into a fact',()=>{const f=fixture();const {d}=episode(f);assertion(f,'belief',[d.biological.id]);const a=select(f).items.find(i=>i.kind==='assertion')!;assert.equal(a.provenance[0].kind,'biological_provenance_only');assert.equal(a.interpretation,'unverified_assertion');assert(!JSON.stringify(a).includes('activity'));});
test('Broken semantic provenance excludes only the optional assertion',()=>{const f=fixture();episode(f);assertion(f,'broken',['does-not-exist']);const s=select(f);assert(s.items.some(i=>i.kind==='episode'));assert(!s.items.some(i=>i.id==='broken'));assert(s.manifest.excluded.some(e=>e.reason==='unresolved assertion source'));});
test('Supersession excludes old assertion and contradiction is disclosed symmetrically',()=>{const f=fixture();const {d}=episode(f);assertion(f,'old',[d.event.id]);assertion(f,'new',[d.event.id],{supersedes:'old'});assertion(f,'alternative',[d.event.id],{contradictions:['new']});const s=select(f,{},'internal',[],{...MEMORY_LIMITS,episodes:0,totalBytes:12000});assert(!s.items.some(i=>i.id==='old'));assert(s.items.find(i=>i.id==='new')!.contradictions.includes('alternative'));assert(s.items.find(i=>i.id==='alternative')!.contradictions.includes('new'));});
test('Invalid and cyclic supersession do not silently become current beliefs',()=>{const f=fixture();const {d}=episode(f);assertion(f,'a',[d.event.id],{supersedes:'b'});assertion(f,'b',[d.event.id],{supersedes:'a'});assertion(f,'c',[d.event.id],{supersedes:'missing'});assert(!select(f).items.some(i=>i.kind==='assertion'));});
test('Cyclic assertion provenance fails closed',()=>{const f=fixture();assertion(f,'a',['b']);assertion(f,'b',['a']);assert.equal(select(f).items.length,0);});
test('Direct older reference outranks newer irrelevant history',()=>{const f=fixture();episode(f,1,{at:'2026-09-16T00:00:00.000Z'});for(let n=2;n<=20;n++)episode(f,n);assert.equal(select(f,{referenceIds:['d1:event']}).items[0].id,'d1:episode');});
for(const field of ['projectIds','taskIds'] as const)test('Deterministic structured '+field+' matching',()=>{const f=fixture();episode(f,1,{project:'orchard',task:'read'});episode(f,2);const s=select(f,{[field]:[field==='projectIds'?'orchard':'read']});assert.equal(s.items[0].id,'d1:episode');assert.match(s.manifest.reasons['d1:episode'],/same/);});
test('Lexical overlap is explicit and no semantic similarity is invented',()=>{const f=fixture();episode(f,1,{text:'orchard pruning notes'});episode(f,2,{text:'unrelated calculations'});const s=select(f,{text:'orchard pruning'});assert.equal(s.items[0].id,'d1:episode:artifact');assert.equal(s.manifest.reasons[s.items[0].id],'lexical token overlap');});
test('Recency and stable ID order break ties independently of input order',()=>{const f=fixture();episode(f,2);episode(f,1,{at:'2026-09-18T00:00:00.000Z'});episode(f,3);const a=select(f);f.archive.decisions.reverse();f.archive.episodes.reverse();assert.deepEqual(select(f),a);assert.equal(a.items[0].id,'d2:episode');});
test('Zero relevant memories returns an empty selection',()=>{const f=fixture();f.bio.input!.observedAt='2027-01-01T00:00:00.000Z';episode(f);assert.equal(select(f).items.length,0);});
test('Explicit category and byte budgets reject invalid limits and drop whole items',()=>{const f=fixture();episode(f,1,{text:'x'.repeat(100000)});const s=select(f,{},'internal',[],{...MEMORY_LIMITS,totalBytes:500});assert.equal(s.items.length,0);assert(s.manifest.bytes<=500);assert.throws(()=>select(f,{},'internal',[],{...MEMORY_LIMITS,episodes:-1}));assert.throws(()=>select(f,{},'internal',[],{} as typeof MEMORY_LIMITS));assert.equal(utf8Excerpt('🍃abc',3),'');});
for(const n of [10,100,1000])test('Bounded deterministic fixture history '+n,()=>{const f=fixture();for(let i=1;i<=n;i++)episode(f,i,{text:'note '+i});const start=performance.now(),s=select(f,{referenceIds:['d1:event']});assert(s.items.length<=7);assert(s.manifest.bytes<=4500);assert.equal(s.items[0].id,'d1:episode');assert.deepEqual(select(f,{referenceIds:['d1:event']}),s);const c=compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,12000,undefined,f.archive);assert(Buffer.byteLength(c.text)<=12000);assert(performance.now()-start<10000);});
test('Context selection/hash is stable and present/past/assertion/artifact sections stay separate',()=>{const f=fixture();episode(f,1,{text:'PRIVATE_ARTIFACT_CANARY'});assertion(f,'belief',['d1:event']);const c=compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,12000,undefined,f.archive);assert.equal(c.hash,compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,12000,undefined,f.archive).hash);assert.equal(c.hash,digest(c.text));assert(c.manifest.memory?.manifest.selectedIds.length);const x=JSON.parse(c.text);assert.equal(x.currentEvent.id,'current');assert(x.relevantPastExperiences.length);assert(x.currentSemanticSelfMemory.length);assert(x.relevantPriorArtifacts.length);assert(!c.text.includes('HIDDEN_REASONING_CANARY'));assert(!JSON.stringify(publicState(f.o,f.life)).includes('PRIVATE_ARTIFACT_CANARY'));});
test('Final context budget drops optional memory while preserving mandatory context',()=>{const f=fixture();episode(f,1,{text:'x'.repeat(10000)});const empty=compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS);const bound=Buffer.byteLength(empty.text)+50,c=compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,bound,undefined,f.archive);assert(Buffer.byteLength(c.text)<=bound);assert.equal(c.manifest.memory?.manifest.selectedIds.length,0);assert.throws(()=>compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,1,undefined,f.archive));});
for(const defect of ['date','visibility','source','owner','record'])test('Malformed optional '+defect+' is excluded without breaking other recall',()=>{const f=fixture();const {e}=episode(f);episode(f,2);if(defect==='date')e.at='2026-02-30T00:00:00.000Z';if(defect==='visibility')e.visibility='arbitrary';if(defect==='source')e.source='missing';if(defect==='owner')e.organismId='wrong';if(defect==='record')e.record={} as typeof e.record;const s=select(f);assert(s.items.some(i=>i.id==='d2:episode'));assert(!s.items.some(i=>i.id==='d1:episode'));assert(s.manifest.excluded.length);});
test('Credentials cannot become eligible via reviewed text or assertions',()=>{const f=fixture();const m=legacy(f);m.text='api_key=DO_NOT_DISCLOSE';episode(f,1,{text:'Bearer DO_NOT_DISCLOSE'});assertion(f,'belief',['d1:event'],{text:'password=DO_NOT_DISCLOSE'});const s=select(f,{},'internal',[review(f,m)]);assert(!JSON.stringify(s).includes('DO_NOT_DISCLOSE'));assert(s.manifest.excluded.filter(e=>e.reason.includes('credential')).length>=3);});
test('Unresolved mandatory identity remains fatal',()=>{const f=fixture();f.life.organismId='wrong';assert.throws(()=>select(f));});
test('Duplicate canonical source IDs are not assigned competing provenance',()=>{const f=fixture();episode(f,1);episode(f,1);assert.equal(select(f).items.length,0);});
test('A public source does not grant provider disclosure to a derived private assertion',()=>{const f=fixture();const a=assertion(f,'belief',[f.bio.id]);assert.equal(select(f,{},'provider').items.length,0);assert.equal(select(f,{},'provider',[review(f,a,{provider:true})]).items.length,1);});

test('Actual V2 artifact and assertion recall survive fresh connection/restart without provider or biology advancement',{skip},()=>activeFixture(async(h,schema,url)=>{
 const f=await h.claim('memory-test');const planner={propose:async(c:Parameters<ProductFallback['propose']>[0])=>({...await new ProductFallback().propose(c),kind:'PROPOSAL' as const,tool:'local_artifact' as const,arguments:{text:'PRIVATE_DURABLE_NOTE'},changes:[{kind:'assertion' as const,assertion:{id:'remember',text:'An unverified self assertion',sources:[c.sources[0]],confidence:0.5,author:'planner' as const,verified:false as const,supersedes:null,contradictions:[]}}]})};
 const p=await h.prepare(f,planner,{...CLOSED_PERMISSIONS,execution:true,localArtifacts:true});const d=await h.commit(f,p);assert(!JSON.stringify(publicDecision(d)).includes('PRIVATE_DURABLE_NOTE'));
 const restarted=new pg.Pool({connectionString:url,options:`-c search_path=${schema}`});try{
 const o=(await restarted.query('SELECT state FROM genesis_organisms')).rows[0].state,life=(await restarted.query('SELECT record FROM genesis_life_state')).rows[0].record;
 const archive=await loadMemoryArchive(restarted,o.id,life.revision);const bio=new SavedObservationAdapter(o.id).accept({id:'read-only-synthetic',kind:'digital-event',source:'test',observedAt:new Date().toISOString()});const s=retrieveMemory(o,life,bio,archive);
 assert(s.items.some(i=>i.kind==='artifact'&&i.excerpt==='PRIVATE_DURABLE_NOTE'));assert(s.items.some(i=>i.id==='remember'));assert(!JSON.stringify(archive).includes('rationale'));assert.equal((await restarted.query('SELECT count(*) AS n FROM genesis_decisions')).rows[0].n,'8');
 const ctx=compileContext(o,life,bio,CLOSED_PERMISSIONS,12000,undefined,archive);assert(ctx.text.includes('PRIVATE_DURABLE_NOTE'));assert(!compileContext(o,life,bio,{...CLOSED_PERMISSIONS,llm:true},12000,undefined,archive).text.includes('PRIVATE_DURABLE_NOTE'));
 await assert.rejects(loadMemoryArchive(restarted,'wrong',life.revision));await assert.rejects(loadMemoryArchive(restarted,o.id,life.revision+1));
 }finally{await restarted.end();}
}));
test('One-shot preparation and commit recompile the same retrieved context; no extra cycle authority',{skip},()=>oneShotFixture(async(h,g)=>{
 await authorize(h,g);const f=await h.claim(g.id),p=await h.prepare(f,{identity:g.planner.identity,planner:new ProductFallback()});assert(p.decision.lifeContext.contextManifest.memory);const d=await h.commit(f,p);assert.equal(d.cycle,8);await assert.rejects(h.claim(g.id));assert.equal((await h.pool.query('SELECT enabled FROM genesis_schedule')).rows[0].enabled,false);
}));
test('Database discovery reports bounds and does not write or expose historical provider payloads',async()=>{const seen:string[]=[];const db={query:async(sql:string)=>{seen.push(sql);if(sql.includes('SELECT o.state'))return {rows:[{id:'fixture',revision:1}]};return {rows:[]};}} as unknown as Parameters<typeof readMemoryArchive>[0];const a=await readMemoryArchive(db,'fixture',1);assert(a.complete);assert(seen.every(s=>!/(INSERT|UPDATE|DELETE|CREATE)/.test(s)));assert(seen.every(s=>!s.includes("record->'reasoning'")));});

test('Stored subject tags are matched without inventing semantic similarity',()=>{const f=fixture(),{d}=episode(f);Object.assign(d.event,{recall:{...EMPTY_QUERY,subjects:['orchard']}});const s=select(f,{subjects:['orchard']});assert.equal(s.manifest.reasons['d1:episode'],'same subject');});
test('Provider cannot gain disclosure by reviewing an assertion whose sources remain private',()=>{const f=fixture(),{d}=episode(f),a=assertion(f,'a',[d.event.id]);const s=select(f,{},'provider',[review(f,a,{provider:true})]);assert(!s.items.some(i=>i.id==='a'));});
test('Semantic duplicate content/provenance is deduplicated without suppressing distinct sources',()=>{const f=fixture(),{d}=episode(f);assertion(f,'a',[d.event.id]);assertion(f,'b',[d.event.id]);assertion(f,'c',[d.biological.id]);const s=select(f,{},'internal',[],{...MEMORY_LIMITS,episodes:0,totalBytes:12000});assert.equal(s.items.length,2);assert(s.manifest.excluded.some(e=>e.reason==='duplicate derived content/provenance'));});
test('Incomplete archive status is explicit in compiled context and manifest',()=>{const f=fixture();f.archive.complete=false;const c=compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,12000,undefined,f.archive);assert.equal(c.manifest.memory?.manifest.discoveryComplete,false);assert.equal(JSON.parse(c.text).memoryRetrieval.discoveryComplete,false);});
test('Unsafe manifest key cannot become object prototype state',()=>{const f=fixture(),m=legacy(f);m.id='__proto__';assert.equal(select(f).items.length,0);assert.equal(({} as {polluted?:boolean}).polluted,undefined);});
test('Legacy internal review integrates into compiler without changing original records',()=>{const f=fixture(),m=legacy(f),r=review(f,m),before=digest(f.o);const c=compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,12000,undefined,f.archive,[r]);assert(c.manifest.selectedIds.includes(m.id));assert(c.text.includes(m.text));assert.equal(digest(f.o),before);assert(!compileContext(f.o,f.life,f.bio,{...CLOSED_PERMISSIONS,llm:true},12000,undefined,f.archive,[r]).text.includes(m.text));});
test('Stored row envelope mismatch is excluded without repairing a source',{skip},()=>activeFixture(async(h)=>{
 const owner=(await h.pool.query('SELECT state FROM genesis_organisms')).rows[0].state,life=(await h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record;
 await h.tx(c=>c.query('INSERT INTO genesis_memories(id,decision_id,at,record) VALUES($1,$2,$3,$4)',['envelope-id','fixture-history-1',owner.bornAt,{id:'wrong-record-id',at:owner.bornAt,sourceDecision:'fixture-history-1',salience:1,text:'should not be recalled'}]));
 const archive=await loadMemoryArchive(h.pool,owner.id,life.revision);const bio=new SavedObservationAdapter(owner.id).accept({id:'synthetic-read',kind:'digital-event',source:'test',observedAt:new Date().toISOString()});const s=retrieveMemory(owner,life,bio,archive);assert(s.manifest.excluded.some(e=>e.reason==='malformed legacy memory'));assert.equal((await h.pool.query('SELECT record FROM genesis_memories')).rows[0].record.id,'wrong-record-id');
}));
test('Oversized persisted artifact is excluded with an explicit bound rather than injected',{skip},()=>activeFixture(async(h)=>{
 const f=await h.claim('large-artifact'),p=await h.prepare(f,new ProductFallback(),{...CLOSED_PERMISSIONS,execution:true});const e=p.decision.memory.episode;
 // Deliberately corrupted/oversized fixture row, not an actual artifact executor.
 Object.assign(e.record as object,{localArtifact:'x'.repeat(70000)});
 await h.tx(c=>c.query('INSERT INTO genesis_decisions(id,cycle,at,record) VALUES($1,8,$2,$3)',['oversize',e.at,{...p.decision,id:'oversize',cycle:8,memory:{...p.decision.memory,episode:{...e,source:'oversize'}}}]));
 await h.pool.query("INSERT INTO genesis_life_events(id,organism_id,at,record) VALUES($1,'genesis',$2,$3)",[e.id,e.at,{...e,source:'oversize'}]);
 const o=(await h.pool.query('SELECT state FROM genesis_organisms')).rows[0].state,l=(await h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record;
 const archive=await loadMemoryArchive(h.pool,o.id,l.revision),bio=new SavedObservationAdapter(o.id).accept({id:'future-read',kind:'digital-event',source:'test',observedAt:new Date().toISOString()});const s=retrieveMemory(o,l,bio,archive);assert(s.manifest.excluded.some(x=>x.reason==='artifact source exceeds discovery byte bound'));assert(!s.items.some(x=>x.kind==='artifact'));
}));
test('Changed selected assertion invalidates one-shot context binding',{skip},()=>oneShotFixture(async(h,g)=>{
 const life=(await h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record;
 life.environment=[{id:'past-source',text:'A factual source record',source:'fixture',visibility:'public',at}];
 life.semanticMemory=[{id:'past-belief',text:'Original unverified belief',sources:['past-source'],confidence:0.5,author:'planner',verified:false,supersedes:null,contradictions:[]}];
 await h.pool.query('UPDATE genesis_life_state SET record=$1',[life]);
 await authorize(h,g);const f=await h.claim(g.id),p=await h.prepare(f,{identity:g.planner.identity,planner:new ProductFallback()});assert(p.decision.lifeContext.contextManifest.memory!.manifest.selectedIds.includes('past-belief'));
 // Simulate an inconsistent trusted writer without altering an append-only record.
 await h.pool.query("UPDATE genesis_life_state SET record=jsonb_set(record,'{semanticMemory,0,text}','\"Changed unverified belief\"')");
 await assert.rejects(h.commit(f,p),/context changed/);assert.equal((await h.pool.query('SELECT count(*) AS n FROM genesis_decisions')).rows[0].n,'7');
}));
test('An explicitly empty archive never resurrects a missing legacy row from the organism cache',()=>{const f=fixture(),m=legacy(f);f.o.memory.push(m);f.archive.legacy=[];const s=select(f,{},'internal',[review(f,m)]);assert.equal(s.items.length,0);assert.equal(s.manifest.discovered,0);});
test('Credential-like recall query cannot enter the newly added context metadata',()=>{const f=fixture();f.bio.input!.recall={...EMPTY_QUERY,text:'api_key=QUERY_CANARY'};assert.throws(()=>compileContext(f.o,f.life,f.bio,CLOSED_PERMISSIONS,12000,undefined,f.archive),/Credential-like recall query/);});
