import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {once} from 'node:events';import {readFileSync} from 'node:fs';
import {oneShotFixture,authorize} from './support/one-shot-fixture.ts';
import {OneShotController} from '../server/one-shot.ts';import {identities,validateGrant} from '../server/one-shot-spec.ts';import {ProductFallback} from '../core/v2/planner.ts';import {digest} from '../core/v2/identity.ts';import type {PlannerV2,Proposal} from '../core/v2/contracts.ts';import type {ProviderAdmission} from '../server/provider-admission.ts';import {awakeningEventSchema} from '../server/awakening-event.ts';
const skip=!process.env.TEST_DATABASE_URL;const fallback=new ProductFallback();const selected={identity:'product-deterministic-v1',planner:fallback};
function planning(kind:Proposal['kind'],tool:Proposal['tool']=null):PlannerV2{return {propose:async c=>({...await fallback.propose(c),kind,tool,arguments:{text:'One bounded local fixture artifact'},deferUntil:kind==='DEFER'?'2030-01-01T00:00:00Z':null,assistance:kind==='REQUEST_ASSISTANCE'?'Please review locally.':null})};}
async function state(h:OneShotController){const g=(await h.pool.query('SELECT status,result FROM genesis_execution_grants ORDER BY id')).rows;const n=Number((await h.pool.query('SELECT count(*) AS n FROM genesis_decisions')).rows[0].n);const l=(await h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record;assert.equal(l.executionLock,'CLOSED');assert.equal((await h.pool.query('SELECT enabled FROM genesis_schedule')).rows[0].enabled,false);return {g,n,l};}
for(const [name,p] of [['valid abstention',planning('ABSTAIN')],['defer',planning('DEFER')],['local reflection',planning('PROPOSAL','local_reflection')],['local artifact',planning('PROPOSAL','local_artifact')],['assistance',planning('REQUEST_ASSISTANCE')],['planner failure',{propose:async()=>{throw Error('fixture failure');}}]] as const)test('One-shot consumes: '+name,{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);const d=await h.run(g.id,async()=>({...selected,planner:p}));assert.equal(d.cycle,8);const s=await state(h);assert.equal(s.n,8);assert.equal(s.g[0].status,'CONSUMED');await assert.rejects(h.run(g.id,async()=>selected));assert.equal((await state(h)).n,8);assert.equal(d.biological.status,'not_applied');assert.equal(d.biological.executedThisCycle,false);}));
test('One-shot policy denial terminates once',{skip},()=>oneShotFixture(async(h,g)=>{g.permission.localArtifacts=false;g.permissionHash=digest(g.permission);await authorize(h,g);const d=await h.run(g.id,async()=>({...selected,planner:planning('PROPOSAL','local_artifact')}));assert.equal(d.policy?.verdict,'DENY');assert.equal(d.action.status,'not_executed');assert.equal((await state(h)).g[0].result,'DENIED');}));
for(const mismatch of ['organism','runtime','policy','constitution','mode','permission','revision','life revision','count','authorization'])test('One-shot rejects wrong '+mismatch,{skip},()=>oneShotFixture(async(h,g)=>{
 if(mismatch==='organism')g.organismId='wrong';if(mismatch==='runtime')g.runtime.sha256='0'.repeat(64);if(mismatch==='policy')g.policy.hash='0'.repeat(64);if(mismatch==='constitution')g.constitution.hash='0'.repeat(64);if(mismatch==='mode')g.mode.hash='0'.repeat(64);if(mismatch==='permission')g.permissionHash='0'.repeat(64);if(mismatch==='revision')g.stateRevision++;if(mismatch==='life revision')g.lifeRevision++;
 if(mismatch==='count'){assert.throws(()=>validateGrant({...g,expectedDecisionCount:8}));return;}
 await assert.rejects(async()=>{await h.propose(g);await h.authorize(g.id,{payloadHash:digest(g),issuer:g.issuer,reference:mismatch==='authorization'?'wrong':g.authorizationReference});await h.claim(g.id);});assert.equal((await state(h)).n,7);
}));
for(const phase of ['before claim','after claim','during planning','before commit'])test('One-shot revocation/cancellation '+phase,{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);if(phase==='before claim'){await h.revoke(g.id,'operator-revocation');await assert.rejects(h.claim(g.id));}else{const f=await h.claim(g.id);if(phase==='during planning'){await assert.rejects(h.prepare(f,{...selected,planner:{propose:async c=>{await h.cancel(f);return fallback.propose(c);}}}));}else if(phase==='before commit'){const p=await h.prepare(f,selected);await h.cancel(f);await assert.rejects(h.commit(f,p));}else{await h.revoke(g.id,'operator-revocation');await assert.rejects(h.prepare(f,selected));}}const s=await state(h);assert.equal(s.n,7);assert.equal(s.g[0].status,'REVOKED');}));
test('One-shot expiration is durable, not an unlock',{skip},async t=>oneShotFixture(async(h,g)=>{await authorize(h,g);t.mock.method(Date,'now',()=>Date.parse(g.expiresAt)+1);await assert.rejects(h.claim(g.id));assert.equal((await state(h)).g[0].status,'EXPIRED');}));
test('One-shot simultaneous claim and commit: single winner',{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);const second=new OneShotController(h.pool);const claims=await Promise.allSettled([h.claim(g.id),second.claim(g.id)]);const wins=claims.filter(x=>x.status==='fulfilled');assert.equal(wins.length,1);const f=(wins[0] as PromiseFulfilledResult<Awaited<ReturnType<typeof h.claim>>>).value;const p=await h.prepare(f,selected);const commits=await Promise.allSettled([h.commit(f,p),second.commit(f,p)]);assert.equal(commits.filter(x=>x.status==='fulfilled').length,1);assert.equal((await state(h)).n,8);}));
test('One-shot second grant cannot create decision nine',{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);await h.run(g.id,async()=>selected);const next={...g,id:'second-grant',stateRevision:g.stateRevision+1,lifeRevision:g.lifeRevision+1};await authorize(h,next);await assert.rejects(h.claim(next.id));assert.equal((await state(h)).n,8);}));
for(const phase of ['before_claim','after_claim','before_commit','after_intent'])test('One-shot fresh-process crash '+phase,{skip,timeout:20000},()=>oneShotFixture(async(h,g,schema,url)=>{
 await authorize(h,g);const child=spawn(process.execPath,['tests/support/one-shot-crash.ts',phase],{env:{NODE_ENV:'test',PATH:process.env.PATH,TEST_DATABASE_URL:url,FIXTURE_SCHEMA:schema},stdio:['ignore','pipe','pipe']});let err='';child.stderr.on('data',x=>err+=x);const [code]=await once(child,'exit');assert.equal(code,77,err);const restarted=new OneShotController(h.pool);assert.equal((await state(h)).n,7);
 if(phase==='before_claim'){assert.equal((await state(h)).g[0].status,'AUTHORIZED');await restarted.run(g.id,async()=>selected);assert.equal((await state(h)).n,8);return;}
 assert.equal((await state(h)).g[0].status,'CLAIMED');await assert.rejects(restarted.claim(g.id));await h.tx(async c=>{await c.query("SELECT set_config('genesis.oneshot_grant',$1,true),set_config('genesis.oneshot_lease',lease,true) FROM genesis_execution_grants WHERE id=$1",[g.id]);await c.query("UPDATE genesis_organisms SET lease_until=now()-interval '1 second'");});await restarted.recoverExpired(g.id);assert.equal((await state(h)).g[0].status,'AMBIGUOUS');await authorize(h,{...g,id:'replacement'});await assert.rejects(restarted.claim('replacement'));assert.equal((await state(h)).n,7);
 const intents=Number((await h.pool.query('SELECT count(*) AS n FROM genesis_action_intents')).rows[0].n);assert.equal(intents,phase==='after_intent'?1:0);
}));
test('One-shot stale state fails commit and retains seven',{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);const f=await h.claim(g.id);const p=await h.prepare(f,selected);await h.pool.query('UPDATE genesis_life_state SET revision=revision+1');await assert.rejects(h.commit(f,p));assert.equal((await state(h)).n,7);}));
const admission:ProviderAdmission={version:'1.0.0',provider:'fixture',model:'fixture-model',transport:{id:'mock',codeHash:'1'.repeat(64)},tokenCounter:{id:'mock-counter',evidence:'TEST ONLY exact mock token count'},rateCard:{reference:'TEST ONLY invented tariff',sha256:'2'.repeat(64),inputMicrosPerToken:1,outputMicrosPerToken:1,coversAllBillableUsage:true},maximumInputTokens:12000,maximumOutputTokens:1200,perAttemptMicros:50000,perCycleMicros:50000,dailyMicros:50000,timeoutMs:30,automaticRetries:0,secretReference:'fixture:no-secret',reviewReference:'fixture-review'};
for(const mode of ['success','timeout','unadmitted planner','token budget'])test('One-shot provider '+mode,{skip},()=>oneShotFixture(async(h,g)=>{g.permission={...g.permission,llm:true,maxAttempts:1,maxCostMicros:50000};g.permissionHash=digest(g.permission);g.planner={identity:'provider:fixture-model',provider:'fixture',model:'fixture-model',admissionHash:digest(admission)};await authorize(h,g);let calls=0;
 const run=()=>h.run(g.id,async f=>mode==='unadmitted planner'?{identity:g.planner.identity,planner:fallback}:h.providerPlanner(f,{admission,counter:{id:admission.tokenCounter.id,model:'fixture-model',provenance:admission.tokenCounter.evidence,count:()=>mode==='token budget'?12001:100},transport:{...admission.transport,send:async req=>{calls++;if(mode==='timeout')return new Promise(()=>{});return {id:'mock-response',requestId:'mock-request',model:req.model,usage:{inputTokens:100,outputTokens:20},proposal:{schemaVersion:2,id:'p',contextHash:req.contextHash,kind:'ABSTAIN',intent:'No local task',taskId:null,projectId:null,tool:null,arguments:{text:''},citations:[],rationale:'Fixture rationale',cost:{namespace:'OPERATIONAL',maxMicros:0},uncertainty:'fixture',deferUntil:null,assistance:null,changes:[],planner:'ignored'}};}}}));
 if(['timeout','unadmitted planner'].includes(mode))await assert.rejects(run());else await run();const s=await state(h);assert.equal(s.g[0].status,mode==='timeout'?'AMBIGUOUS':mode==='unadmitted planner'?'FAILED':'CONSUMED');assert.equal(calls,['token budget','unadmitted planner'].includes(mode)?0:1);await assert.rejects(h.claim(g.id));
}));
test('Neutral event rejects extra directives; identities include event and mode',()=>{assert.equal(identities().mode.hash.length,64);assert.throws(()=>awakeningEventSchema.parse({danger:true,makeMoney:true}));});
test('No one-shot authorization entry in boot, API, CLI or scheduler',()=>{for(const p of ['runtime/main.ts','runtime/http.ts','runtime/scheduler.ts','scripts/run-life.mjs','scripts/demo.ts'])assert(!readFileSync(p,'utf8').includes('OneShotController'),p);});

test('Authorized fixture grant cannot be consumed by scheduler, API, CLI or environment flags',{skip},()=>oneShotFixture(async(h,g,_schema,url)=>{
 const [{GenesisService},{LifeStore},{readConfig},{LifeScheduler},{handleRequest}]=await Promise.all([import('../runtime/service.ts'),import('../server/store.ts'),import('../runtime/config.ts'),import('../runtime/scheduler.ts'),import('../runtime/http.ts')]);
 await authorize(h,g);const config=readConfig({DATABASE_URL:url,GENESIS_OPERATOR_TOKEN:'test-operator-token-more-than-24-characters',GENESIS_AUTONOMY_ENABLED:'true',GENESIS_EXECUTION_ENABLED:'true',GENESIS_ONE_SHOT_GRANT:g.id,OPENAI_API_KEY:'not-a-real-key',OPENAI_MODEL:'environment-bypass-model'});const service=new GenesisService(new LifeStore(h.pool),config);
 await new LifeScheduler(service).tick();await assert.rejects(service.advance('bypass',undefined,true));
 for(const path of ['/api/cycle','/api/control']){const r=await handleRequest(new Request('http://test'+path,{method:'POST',headers:{authorization:'Bearer '+config.operatorToken},body:JSON.stringify({grantId:g.id,enabled:true})}),service);assert.equal(r.status,423);}
 for(const file of ['scripts/run-life.mjs','scripts/demo.ts','scripts/check-llm.ts']){const child=spawn(process.execPath,[file],{env:{NODE_ENV:'test',PATH:process.env.PATH,GENESIS_ONE_SHOT_GRANT:g.id,GENESIS_EXECUTION_ENABLED:'true'},stdio:['ignore','ignore','pipe']});let err='';child.stderr.on('data',x=>err+=x);const [code]=await once(child,'exit');assert.notEqual(code,0);assert.match(err,/EXECUTION_NOT_AUTHORIZED/);}
 const s=await state(h);assert.equal(s.n,7);assert.equal(s.g[0].status,'AUTHORIZED');
}));
test('Generic OPEN and writer marker cannot substitute for one-shot grant',{skip},()=>oneShotFixture(async(h,g)=>{
 await authorize(h,g);await h.pool.query("UPDATE genesis_life_state SET record=jsonb_set(record,'{executionLock}','\"OPEN\"')");await assert.rejects(h.claim(g.id));await assert.rejects(h.tx(c=>c.query("UPDATE genesis_organisms SET phase='planning'")));await h.pool.query("UPDATE genesis_life_state SET record=jsonb_set(record,'{executionLock}','\"CLOSED\"')");assert.equal((await state(h)).n,7);
}));
test('Grant payload and terminal status cannot be silently rewritten',{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);await assert.rejects(h.pool.query("UPDATE genesis_execution_grants SET payload=jsonb_set(payload,'{expectedDecisionCount}','8')"));await h.run(g.id,async()=>selected);await assert.rejects(h.pool.query("UPDATE genesis_execution_grants SET status='AUTHORIZED'"));await assert.rejects(h.pool.query('DELETE FROM genesis_execution_grants')); assert.equal((await state(h)).n,8);}));
test('Grant revalidates proposal and context at commit',{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);const f=await h.claim(g.id);const p=await h.prepare(f,selected);p.decision.lifeContext.contextHash='0'.repeat(64);await assert.rejects(h.commit(f,p));await h.fail(f);assert.equal((await state(h)).g[0].status,'FAILED');assert.equal((await state(h)).n,7);}));

test('One-shot cancels a planner that never resolves',{skip},()=>oneShotFixture(async(h,g)=>{await authorize(h,g);await assert.rejects(h.run(g.id,async f=>({...selected,planner:{propose:async()=>{await h.cancel(f);return new Promise(()=>{});}}})));assert.equal((await state(h)).g[0].status,'REVOKED');assert.equal((await state(h)).n,7);}));
