import test from 'node:test';
import assert from 'node:assert/strict';
import {fixtureAdmission,reasoningFixture,TEST_SECRET} from './support/reasoning-fixture.ts';
import {validateAdmission,resolveAdapter,type FixtureScenario} from '../server/reasoning/factory.ts';
import {INSTRUCTIONS,OUTPUT_SCHEMA,environmentSecrets} from '../server/reasoning/contracts.ts';
import {completeWire,buildRequest,cost} from '../server/reasoning/request.ts';
import {ProviderControl} from '../server/provider-control.ts';
import {OneShotController} from '../server/one-shot.ts';
import {digest} from '../core/v2/identity.ts';
const skip=!process.env.TEST_DATABASE_URL;
for(const field of ['provider','model','adapter','format','schemaHash','plannerHash','runtimeHash','counting','rateCard','automaticRetries','maximumAttempts'] as const)test('Pinned admission rejects malformed '+field,()=>{const a:Record<string,unknown>=fixtureAdmission();a[field]=undefined;assert.throws(()=>validateAdmission(a));});
test('Complete schema contains local operation graph and rejects hidden reasoning fields',()=>{const s=JSON.stringify(OUTPUT_SCHEMA);assert(s.includes('project_create'));assert(s.includes('additionalProperties'));assert(!s.includes('financial_transfer'));assert(!s.includes('external_message'));assert(!s.includes('followUp'));assert(INSTRUCTIONS.text.includes('untrusted data'));});
test('Unknown usage is not free; category rounding and multiple categories',()=>{const a=fixtureAdmission();assert.equal(cost(a,{input:1,output:1,reasoning:1,requests:1}),7);for(const u of [{input:1,output:1},{input:1,output:1,reasoning:1,requests:1,unknown:0},{input:12001,output:0,reasoning:0,requests:0}])assert.throws(()=>cost(a,u as Record<string,number>));});
test('Production secret resolver rejects fixture refs and missing configuration generically',async()=>{for(const ref of ['fixture:PROVIDER','env:OTHER_KEY','env:GENESIS_PROVIDER_NONEXISTENT'])await assert.rejects(environmentSecrets.resolve(ref),/CONFIGURATION/);});
test('Fixture adapter refuses non-fixture target',()=>assert.throws(()=>resolveAdapter(fixtureAdmission(),false)));
for(const scenario of ['abstain','valid','defer','assistance'] as FixtureScenario[])test('Admitted one-shot '+scenario+' commits eight only through production boundary',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();let calls=0;const d=await x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:scenario,onFixtureSend:()=>calls++}));assert.equal(d.cycle,8);assert.equal(calls,1);assert.equal(await x.count(),8);await assert.rejects(x.h.claim(x.g.id));const row=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(row.protocolVersion,2);assert.equal(row.status,'received');assert.equal(row.request.wire,completeWire(x.a,row.context));assert(row.request.accounting.bytes>Buffer.byteLength(row.context.text));assert(!JSON.stringify(row).includes(TEST_SECRET));assert.equal((await x.h.pool.query('SELECT status FROM genesis_execution_grants')).rows[0].status,'CONSUMED');assert.equal((await x.h.pool.query('SELECT enabled FROM genesis_schedule')).rows[0].enabled,false);assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_continuous_scopes')).rows[0].n,'0');assert.equal((await x.h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record.executionLock,'CLOSED');}));
for(const scenario of ['malformed','schema','network','5xx','rate_limit','unknown_usage','wrong_admission','secret_echo','timeout','cancel_confirmed','cancel_uncertain'] as FixtureScenario[])test('Provider '+scenario+' stops with seven decisions and no retry',{skip},()=>reasoningFixture(async x=>{if(['timeout','cancel_confirmed','cancel_uncertain'].includes(scenario))x.a.timeoutMs=120;await x.admit();await x.authorize();let calls=0;await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:scenario,onFixtureSend:()=>calls++})));assert.equal(await x.count(),7);assert.equal(calls,1);await assert.rejects(x.h.claim(x.g.id));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert(['received','unknown'].includes(r.status));if(scenario==='unknown_usage')assert.equal(r.costMicros,null);for(const table of ['genesis_provider_attempts','genesis_provider_receipts','genesis_operator_audit','genesis_life_state','genesis_decisions','genesis_recovery_dispositions'])assert(!JSON.stringify((await x.h.pool.query(`SELECT * FROM ${table}`)).rows).includes(TEST_SECRET));}));
test('Missing secret stops before reservation or dispatch',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();let calls=0;await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,secretResolver:{resolve:async()=>{throw Error(TEST_SECRET);}},onFixtureSend:()=>calls++})));assert.equal(calls,0);assert.equal(await x.count(),7);assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_attempts')).rows[0].n,'0');}));
test('Durable receipt permits fresh controller replay without a second send',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);let calls=0;const p=await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++}));const fresh=new OneShotController(x.h.pool);const restored=await fresh.resumeReceived(f);assert.deepEqual(restored,p);await fresh.commit(f,restored);assert.equal(calls,1);assert.equal(await x.count(),8);await assert.rejects(fresh.resumeReceived(f));}));
test('Healthy ownership is not recovered by a second worker',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);const p=x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'timeout'}));while(!(await x.h.pool.query('SELECT id FROM genesis_provider_attempts')).rowCount)await new Promise(r=>setTimeout(r,10));await new ProviderControl(x.h.pool,async()=>{}).recover();assert.notEqual((await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record.status,'unknown');await x.h.cancel(f);await assert.rejects(p);assert.equal(await x.count(),7);}));
for(const revoke of ['admission','authority','disclosure'])test('Durable receipt cannot commit after '+revoke+' change',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id),p=await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,x.options));if(revoke==='admission')await x.call('revoke_provider',{targetId:x.a.id,expectedHash:await x.targetHash('genesis_provider_admissions',x.a.id)});else if(revoke==='authority')await x.h.cancel(f);else await x.h.pool.query("UPDATE genesis_control_state SET review_revision=review_revision+1");await assert.rejects(x.h.commit(f,p));await assert.rejects(x.h.resumeReceived(f));assert.equal(await x.count(),7);}));
test('Admission is separate from execution and immutably audited',{skip},()=>reasoningFixture(async x=>{await x.admit();await assert.rejects(x.h.claim(x.g.id));for(const sql of ["UPDATE genesis_provider_admissions SET payload='{}'",'DELETE FROM genesis_provider_admissions'])await assert.rejects(x.h.pool.query(sql));const v=await x.call('inspect_provider',{targetId:x.a.id});assert(!JSON.stringify(v).includes(TEST_SECRET));assert.equal(await x.count(),7);}));
test('Complete request binds identity and immutable wire; receipt rejects edits',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,x.options));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(buildRequest(x.a,r.context,f,r.request.requestedAt).hash,r.request.hash);assert.notEqual(buildRequest(x.a,r.context,f,new Date(Date.now()+1000).toISOString()).hash,r.request.hash);await assert.rejects(x.h.pool.query("UPDATE genesis_provider_attempts SET record=jsonb_set(record,'{request,wire}','\"tampered\"')"));await assert.rejects(x.h.pool.query('DELETE FROM genesis_provider_receipts'));const v=await x.call('inspect_provider_attempt',{targetId:f.cycleId+':reasoning'});assert(!JSON.stringify(v).includes('Fixture bounded explanation'));assert(!JSON.stringify(v).includes('critical'));assert(!JSON.stringify(v).includes(TEST_SECRET));}));
test('Reported-only counting refuses before dispatch',{skip},()=>reasoningFixture(async x=>{x.a.counting.strategy='PROVIDER_REPORTED_ONLY';await x.admit();await x.authorize();let calls=0;await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++})));assert.equal(calls,0);assert.equal(await x.count(),7);}));

for(const scenario of ['excess_usage','extra_usage','unknown_error','before_timeout'] as FixtureScenario[])test('Conservative liability for '+scenario,{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:scenario})));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(r.status,'unknown');assert.equal(r.costMicros,null);assert(r.reservedMicros>0);assert.equal(await x.count(),7);}));
test('Fresh OS process recovers the identical validated preparation with no dispatch',{skip},()=>reasoningFixture(async x=>{const {spawn}=await import('node:child_process');await x.admit();await x.authorize();const f=await x.h.claim(x.g.id),prepared=await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,x.options));const stdout=await new Promise<string>((resolve,reject)=>{const child=spawn(process.execPath,['tests/support/reasoning-replay-child.ts'],{env:{NODE_ENV:'test',PATH:process.env.PATH,TEST_DATABASE_URL:x.url,PROVIDER_TEST_SCHEMA:x.schema,PROVIDER_TEST_FENCE:JSON.stringify(f)}});let out='',err='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);child.on('exit',code=>code===0?resolve(out):reject(Error(err)));});assert.equal(digest(JSON.parse(stdout)),digest(prepared));await x.h.commit(f,JSON.parse(stdout));assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_attempts')).rows[0].n,'1');assert.equal(await x.count(),8);}));
test('Two workers cannot dispatch the same logical request twice',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);let calls=0;const selected=await x.h.admittedReasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++});const p=await x.h.prepare(f,selected);const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;const pc=new ProviderControl(x.h.pool,async fence=>{await x.h.check(fence);});const out=await Promise.all([pc.reasoningPlanner(f,{...x.options,owner:'second',onFixtureSend:()=>calls++}).propose(r.context),pc.reasoningPlanner(f,{...x.options,owner:'third',onFixtureSend:()=>calls++}).propose(r.context)]);assert.deepEqual(out[0],p.decision.proposal);assert.deepEqual(out[1],p.decision.proposal);assert.equal(calls,1);await x.h.commit(f,p);await assert.rejects(x.h.commit(f,p));}));
test('Request lease expiry recovery preserves unknown liability and refuses receipt replay',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);await assert.rejects(x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'network'})));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;await new ProviderControl(x.h.pool,async()=>{}).recover();await assert.rejects(x.h.resumeReceived(f));assert.equal((await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record.reservedMicros,r.reservedMicros);}));
for(const type of ['authority','disclosure','admission'] as const)test('Revocation during dispatched request: '+type,{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);let sent!:()=>void;const dispatched=new Promise<void>(r=>sent=r);const pending=x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'timeout',onFixtureSend:sent}));const rejected=assert.rejects(pending);await dispatched;if(type==='authority')await x.call('emergency_stop');if(type==='disclosure')await x.h.pool.query('UPDATE genesis_control_state SET review_revision=review_revision+1');if(type==='admission')await x.call('revoke_provider',{targetId:x.a.id,expectedHash:await x.targetHash('genesis_provider_admissions',x.a.id)});await rejected;const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(r.status,'unknown');assert.equal(r.costMicros,null);assert.equal(await x.count(),7);}));
test('Admission unknown factory/schema/counting code cannot be accepted by matching labels',{skip},()=>reasoningFixture(async x=>{for(const mutate of [(a:typeof x.a)=>a.adapter.hash='1'.repeat(64),(a:typeof x.a)=>a.schemaHash='2'.repeat(64),(a:typeof x.a)=>a.counting.hash='3'.repeat(64)]){const a=structuredClone(x.a);mutate(a);await assert.rejects(x.call('propose_provider',{targetId:a.id,payload:a}));}assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_admissions')).rows[0].n,'0');}));
test('Daily budget and complete wire bounds stop before send',{skip},()=>reasoningFixture(async x=>{x.a.counting.maxWireBytes=100;await x.admit();await x.authorize();let calls=0;await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++})));assert.equal(calls,0);assert.equal(await x.count(),7);}));
test('Canonical validated receipt excludes headers and unsupported hidden content',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,x.options));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_receipts')).rows[0].record;assert.deepEqual(Object.keys(r).sort(),['admissionHash','costMicros','proposal','proposalHash','providerRequestId','receivedAt','requestHash','responseHash','responseId','usage','validation'].sort());assert(!JSON.stringify(r).includes(TEST_SECRET));}));
test('Fixture inspection accounts full request without secret or network',{skip},()=>reasoningFixture(async x=>{const {inspectFixtureAdmission}=await import('../server/reasoning/inspection.ts');await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,x.options));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;const v=inspectFixtureAdmission(x.a,r.context,f,r.request.requestedAt);assert.equal(v.requestHash,r.request.hash);assert.equal(v.reservationMicros,r.reservedMicros);assert.equal(v.networkCalls,0);assert(!JSON.stringify(v).includes(TEST_SECRET));}));
test('Actual child process exits after durable receipt; parent recovers without paid retry',{skip},()=>reasoningFixture(async x=>{const {spawn}=await import('node:child_process');await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);const output=await new Promise<string>((resolve,reject)=>{const child=spawn(process.execPath,['tests/support/reasoning-replay-child.ts'],{env:{NODE_ENV:'test',PATH:process.env.PATH,TEST_DATABASE_URL:x.url,PROVIDER_TEST_SCHEMA:x.schema,PROVIDER_TEST_FENCE:JSON.stringify(f),PROVIDER_TEST_PREPARE:'yes'}});let out='',err='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);child.on('exit',code=>code===0?resolve(out):reject(Error(err)));});const p=await x.h.resumeReceived(f);assert.equal(digest(p),digest(JSON.parse(output)));await x.h.commit(f,p);assert.equal(await x.count(),8);assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_attempts')).rows[0].n,'1');}));
test('Response identity collision never overwrites receipt or fabricates completion',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);await x.h.pool.query("INSERT INTO genesis_provider_attempts(id,cycle_id,grant_id,record) VALUES('older','older','fixture','{\"status\":\"received\",\"costMicros\":0}')");await x.h.pool.query("INSERT INTO genesis_provider_receipts(attempt_id,provider,response_id,request_hash,admission_hash,record) VALUES('older','fixture','fixture-shared-response',$1,$1,'{}')",['1'.repeat(64)]);await assert.rejects(x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'duplicate_response'})));assert.equal(await x.count(),7);assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_receipts')).rows[0].n,'1');assert.equal((await x.h.pool.query('SELECT record FROM genesis_provider_attempts WHERE cycle_id=$1',[f.cycleId])).rows[0].record.status,'unknown');}));
test('Prepared smoke command remains separate/inert and never imports organism execution',async()=>{const {readFileSync}=await import('node:fs');const s=readFileSync('runtime/provider-smoke.ts','utf8');assert(s.includes("'wx',0o600"));assert(s.includes('SANITIZED_PROVIDER_SMOKE_ONLY'));assert(s.includes('MANAGE_PROVIDER_ADMISSION'));for(const forbidden of ['OneShotController','prepareCycle','compileContext','INSERT INTO','UPDATE genesis'])assert(!s.includes(forbidden));for(const p of ['runtime/main.ts','runtime/http.ts','runtime/service.ts'])assert(!readFileSync(p,'utf8').includes('provider-smoke'));});
test('Neutral HTTP transport sends exact accounted bytes and rejects headers/extra fields without network',async()=>{const original=globalThis.fetch;const a=fixtureAdmission();a.provider='json-gateway';a.adapter.id='json-gateway-v1';a.endpoint='https://reviewed-provider.example/reason';a.secretReference='env:GENESIS_PROVIDER_FIXTURE';let sent='';globalThis.fetch=async(_url,init)=>{sent=init!.body as string;assert.equal((init!.headers as Record<string,string>).authorization,'Bearer '+TEST_SECRET);return new Response(JSON.stringify({responseId:'r',requestId:'q',model:a.model,admissionHash:digest(a),structured:{},usage:{input:0,output:0,reasoning:0,requests:1}}),{status:200});};try{const wire='{"sanitized":"fixture"}';await resolveAdapter(a,false).send(wire,TEST_SECRET,new AbortController().signal);assert.equal(sent,wire);}finally{globalThis.fetch=original;}});
for(const status of [401,429,500])test('HTTP '+status+' returns bounded error, no raw headers/body',async()=>{const original=globalThis.fetch,a=fixtureAdmission();a.provider='json-gateway';a.adapter.id='json-gateway-v1';a.endpoint='https://reviewed-provider.example/reason';a.secretReference='env:GENESIS_PROVIDER_FIXTURE';globalThis.fetch=async()=>new Response(TEST_SECRET,{status,headers:{'x-private':TEST_SECRET}});try{await assert.rejects(resolveAdapter(a,false).send('{}',TEST_SECRET,new AbortController().signal),e=>e instanceof Error&&!e.message.includes(TEST_SECRET));}finally{globalThis.fetch=original;}});

// Faults are injected only at database acknowledgements, never as a production transport.
async function databaseFault(pool:import('pg').Pool,failOn:number,providerOnly=true){
 let commits=0;const wrapped={query:pool.query.bind(pool),connect:async()=>{const c=await pool.connect();let eligible=!providerOnly;return {release:()=>c.release(),query:async(sql:string,args?:unknown[])=>{if(sql.includes('genesis-provider-budget-v1'))eligible=true;const result=await c.query(sql,args);if(sql==='COMMIT'&&eligible&&++commits===failOn)throw Error('FIXTURE_COMMIT_ACK_LOST');return result;}};}} as unknown as import('pg').Pool;return wrapped;
}
test('Lost receipt commit acknowledgement leaves recoverable receipt, never a second request',{skip},()=>reasoningFixture(async x=>{const {ReasoningControl}=await import('../server/reasoning/control.ts');await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);const selected=await x.h.admittedReasoningPlanner(f,x.options);const faulty=new ReasoningControl(await databaseFault(x.h.pool,2),async f=>{await x.h.check(f);});selected.planner.propose=faulty.planner(f,x.options).propose;await assert.rejects(x.h.prepare(f,selected));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(r.status,'received');const p=await x.h.resumeReceived(f);await x.h.commit(f,p);assert.equal(await x.count(),8);assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_attempts')).rows[0].n,'1');}));
test('Crash after durable reservation never dispatches or automatically retries',{skip},()=>reasoningFixture(async x=>{const {ReasoningControl}=await import('../server/reasoning/control.ts');await x.admit();await x.authorize();const f=await x.h.claim(x.g.id),selected=await x.h.admittedReasoningPlanner(f,x.options);let calls=0;selected.planner.propose=new ReasoningControl(await databaseFault(x.h.pool,1),async f=>{await x.h.check(f);}).planner(f,{...x.options,onFixtureSend:()=>calls++}).propose;await assert.rejects(x.h.prepare(f,selected));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(r.status,'reserved');await assert.rejects(new ProviderControl(x.h.pool,async f=>{await x.h.check(f);}).reasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++}).propose(r.context));assert.equal(calls,0);assert.equal(await x.count(),7);}));
test('A second worker during active dispatch cannot recover or dispatch the request',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id);let sent!:()=>void,calls=0;const start=new Promise<void>(r=>sent=r);const p=x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'timeout',onFixtureSend:()=>{calls++;sent();}}));const rejected=assert.rejects(p);await start;const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;const second=new ProviderControl(x.h.pool,async f=>{await x.h.check(f);});await second.recover();await assert.rejects(second.reasoningPlanner(f,{...x.options,owner:'second',onFixtureSend:()=>calls++}).propose(r.context));assert.equal(calls,1);await x.h.cancel(f);await rejected;assert.equal(await x.count(),7);}));
test('Expired ownership becomes unknown without releasing the reservation',{skip},()=>reasoningFixture(async x=>{const {ReasoningControl}=await import('../server/reasoning/control.ts');x.a.timeoutMs=50;await x.admit();await x.authorize();const f=await x.h.claim(x.g.id),selected=await x.h.admittedReasoningPlanner(f,x.options);selected.planner.propose=new ReasoningControl(await databaseFault(x.h.pool,1),async f=>{await x.h.check(f);}).planner(f,x.options).propose;await assert.rejects(x.h.prepare(f,selected));const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;await new Promise(resolve=>setTimeout(resolve,Math.max(0,Date.parse(r.leaseUntil)-Date.now()+20)));await new ProviderControl(x.h.pool,async()=>{}).recover();const after=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(after.status,'unknown');assert.equal(after.costMicros,null);assert.equal(after.reservedMicros,r.reservedMicros);}));
test('Lost canonical fixture commit acknowledgement cannot create a ninth decision',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();const f=await x.h.claim(x.g.id),p=await x.h.prepare(f,await x.h.admittedReasoningPlanner(f,x.options));const h=new OneShotController(await databaseFault(x.h.pool,1,false));await assert.rejects(h.commit(f,p),/ACK_LOST/);assert.equal(await x.count(),8);await assert.rejects(x.h.commit(f,p));await assert.rejects(x.h.claim(x.g.id));assert.equal((await x.h.pool.query('SELECT status FROM genesis_execution_grants')).rows[0].status,'CONSUMED');}));
test('Unknown liability from previous day blocks daily budget admission',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();await x.h.pool.query("INSERT INTO genesis_provider_attempts(id,cycle_id,grant_id,at,record) VALUES('old','old','old',now()-interval '2 days',$1)",[{status:'unknown',costMicros:null,reservedMicros:x.a.dailyMicros}]);let calls=0;await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++})));assert.equal(calls,0);assert.equal(await x.count(),7);}));
test('Reservation over the per-attempt ceiling is rejected before network',{skip},()=>reasoningFixture(async x=>{x.a.rateCard.categories[0].microsNumerator=100;x.a.rateCard.hash=digest({currency:'USD',categories:x.a.rateCard.categories});await x.admit();await x.authorize();let calls=0;await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,onFixtureSend:()=>calls++})));assert.equal(calls,0);assert.equal((await x.h.pool.query('SELECT count(*) n FROM genesis_provider_attempts')).rows[0].n,'0');}));
test('Usage reconciliation failure is atomic and cannot reopen execution',{skip},()=>reasoningFixture(async x=>{await x.admit();await x.authorize();await assert.rejects(x.h.run(x.g.id,f=>x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'network'})));const id='oneshot:'+x.g.id+':reasoning';const pc=new ProviderControl(await databaseFault(x.h.pool,1),async()=>{});await assert.rejects(pc.reconcile(id,{operator:'operator-a',reference:'fixture-billing-proof',costMicros:1}));assert.equal((await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record.status,'reconciled');await assert.rejects(pc.reconcile(id,{operator:'operator-a',reference:'fixture-billing-proof',costMicros:1}));await assert.rejects(x.h.claim(x.g.id));assert.equal(await x.count(),7);}));
for(const change of ['source','review_expiry'])test('Disclosure '+change+' during dispatch retains liability and prevents commit',{skip},()=>reasoningFixture(async x=>{const {disclosureSources,loadDisclosure}=await import('../server/disclosure-store.ts');const {readMemoryArchive}=await import('../server/memory-store.ts');const o=(await x.h.pool.query('SELECT state FROM genesis_organisms')).rows[0].state,l=(await x.h.pool.query('SELECT record FROM genesis_life_state')).rows[0].record;const archive=await readMemoryArchive(x.h.pool,o.id,l.revision);const source=disclosureSources(o,l,archive).find(s=>s.type==='legacy_project_metadata')!;await x.call('review_disclosure',{targetId:source.id,payload:{sourceType:source.type,sourceId:source.id,sourceHash:source.hash,audience:'PROVIDER_DISCLOSURE',decision:'APPROVED',expectedVersion:0,expiresAt:change==='review_expiry'?new Date(Date.now()+1000).toISOString():null}});await x.admit();await x.authorize();let sent!:()=>void;const dispatched=new Promise<void>(r=>sent=r);const f=await x.h.claim(x.g.id);const result=x.h.prepare(f,await x.h.admittedReasoningPlanner(f,{...x.options,fixtureScenario:'timeout',onFixtureSend:sent}));const rejected=assert.rejects(result);await dispatched;if(change==='source'){// Source fixture corruption, not a production update or repair.
 await x.h.pool.query('ALTER TABLE genesis_organisms DISABLE TRIGGER ALL');try{o.businesses[0].name='Changed fixture metadata';await x.h.pool.query('UPDATE genesis_organisms SET state=$1',[o]);}finally{await x.h.pool.query('ALTER TABLE genesis_organisms ENABLE TRIGGER ALL');}}
 await rejected;const r=(await x.h.pool.query('SELECT record FROM genesis_provider_attempts')).rows[0].record;assert.equal(r.status,'unknown');assert.equal(await x.count(),7);if(change==='review_expiry')assert((await loadDisclosure(x.h.pool,o,l,archive)).reviews.some(r=>r.effective==='EXPIRED'));}));
