from common import *
from empirical import canonical_numbers
rows=read('atlas/records.json'); stats=read('VALIDATION_RESULTS.json')['strata']
schemas={}
for r in rows:schemas.setdefault(r['family'],{'fields':sorted(r['descriptor']),'example':r['descriptor']})
write('DESCRIPTOR_SCHEMAS.json',schemas)
write('SUPPORT_STRATA.json',{'strata':[{k:v for k,v in s.items() if k!='by_recording'} for s in stats],'conditional_templates_remain_weak':True})
write('INTERFACE_SPEC.json',{'version':'0.1.0','scope':'Research-only empirical somatic-voltage retrieval and bounded interpolation; no neuronal simulation','entrypoint':'interface.EmpiricalInterface.query','observation':{'quantity':'mean_baseline_subtracted_somatic_voltage','units':'mV','time_ms':[0,500],'step_ms':1,'trials':'source means, not independent trials','calcium_conversion':None,'spike_conversion':None,'rate_conversion':None,'release_conversion':None},'identity_resolution':{'recording':'source dataset + ordinal','class':'conditional T4/T5 source template only','fly':None,'subtype':None,'column':None,'FlyWire_root':None},'coordinate':'author RF/PD localized source pixels; no angle, retina, head or root transform','schemas':'DESCRIPTOR_SCHEMAS.json','candidate_selection':'PROTOCOL.md','numerical_identity':'Integer/float equality and signed-zero equality only; full descriptors and array ordering retained','prohibited_uses':['precursor reconstruction','intracellular dynamics simulation','unmeasured stimulus-family synthesis','individual root physiology assignment','Genesis integration']})
write('SUPPORT_SPEC.json',{'version':'0.1.0','rules':{'DIRECTLY MEASURED':'Exact complete source/frame/observation/descriptor tuple in named recording; provenance and waveform retrieved','INTERPOLATION-SUPPORTED':'Only passing E1 stratum; same recording and all other descriptors fixed; source-tested axis value; strict two-neighbor bracket; duration ratio <=4, offset gap <=2; no joint interpolation','WEAKLY SUPPORTED':'Conditional passing E2 template only on explicit class_template request; not individual prediction. Failed/underpowered/new continuous query returns UNKNOWN','OUT OF DISTRIBUTION / UNKNOWN':'Missing tuple/family/frame/preparation/observation, requested fly/root/subtype/column, unsupported horizon, absent bracket, or invented input field returns no waveform'},'joint_coverage':'atlas/records.json','validation':'SUPPORT_STRATA.json','uncertainty':'UNCERTAINTY.json; null means unbounded/unidentified, never zero','continuous_space_supported':False,'family_transfer_supported':False,'angles_supported':False,'thresholds_sha256':sha(HERE/'PROTOCOL.md'),'interpolation_strata':[s['stratum'] for s in stats if s['stratum'].startswith('E1') and s['meets_registered_criteria']],'template_strata':[s['stratum'] for s in stats if s['stratum'].startswith('E2') and s['meets_registered_criteria']]})
print('Specifications written; not yet frozen until validation.')
