/** Separate, versioned LOCAL authority. No environment-string admission or public issuance endpoint. */
import {z} from 'zod';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {CONSTITUTION_HASH,digest} from '../core/v2/identity.ts';
import {EVENT_KINDS,LOCAL_PERMISSION} from '../core/v2/continuous.ts';
const hash=z.string().regex(/^[a-f0-9]{64}$/),id=z.string().min(1).max(180);
export const FORBIDDEN=['biology','wallet','transfers','trading','purchases','hiring','token_launch','internet','messaging','social','shell','filesystem_execution','live_provider'] as const;
export const scopeSchema=z.object({version:z.literal(1),kind:z.literal('CONTINUOUS_LOCAL_V1'),id,organismId:id,runtimeHash:hash,constitutionHash:hash,policyHash:hash,biologicalMode:z.literal('SAVED-OBSERVATION-ONLY'),planner:z.object({kind:z.literal('LOCAL_DETERMINISTIC'),identity:id,provider:z.null(),model:z.null()}).strict(),allowedEvents:z.array(z.enum(EVENT_KINDS)).min(1),allowedEffects:z.array(z.enum(['local_reflection','local_artifact','life_changes'])),forbidden:z.array(z.string()),scheduling:z.boolean(),permissionHash:hash,minimumPriorDecisions:z.number().int().min(7),maxCycles:z.number().int().min(1).max(10000),windowMs:z.number().int().min(1000).max(86400000),maxCyclesPerWindow:z.number().int().min(1).max(10000),maxConcurrent:z.literal(1),maxCostPerCycleMicros:z.number().int().min(0).max(1000000),maxCostPerWindowMicros:z.number().int().min(0).max(10000000),leaseMs:z.number().int().min(50).max(300000),plannerTimeoutMs:z.number().int().min(10).max(120000),maxAttemptsPerEvent:z.number().int().min(1).max(5),backoffMs:z.number().int().min(1).max(3600000),maxDepth:z.number().int().min(0).max(50),maxFollowups:z.number().int().min(0).max(10),maxImmediatePerRoot:z.number().int().min(1).max(100),minimumDelayMs:z.number().int().min(0).max(86400000),issuedAt:z.string().datetime(),expiresAt:z.string().datetime(),issuer:id,authorizationReference:id}).strict();
export type ContinuousScope=z.infer<typeof scopeSchema>;
const sha=(p:string)=>createHash('sha256').update(readFileSync(new URL('../'+p,import.meta.url))).digest('hex');
export function continuousIdentity(){const files=['core/v2/disclosure.ts','server/disclosure-store.ts','server/operator-auth.ts','server/operator-control.ts','server/operator-transaction.ts','runtime/operator-schema-v1.sql','package.json','package-lock.json','core/v2/identity.ts','core/v2/biology.ts','core/v2/intents.ts','server/intent-journal.ts','server/saved-provenance.ts','server/one-shot-authority.ts','server/one-shot-spec.ts','server/provider-control.ts','runtime/preparation-schema.sql','runtime/one-shot-schema.sql','core/v2/continuous.ts','server/continuous-spec.ts','server/continuous-authority.ts','server/continuous.ts','server/continuous-worker.ts','runtime/continuous-schema.sql','core/v2/contracts.ts','core/v2/cycle.ts','core/v2/context.ts','core/v2/planner.ts','core/v2/policy.ts','core/v2/life-state.ts','core/v2/operations.ts','core/v2/operational-context.ts','core/v2/memory.ts','server/memory-store.ts','server/commit-v2.ts','server/assistance-intake.ts'];return {runtimeHash:digest({version:'continuous-local-v1.0.2',node:process.version,platform:process.platform,architecture:process.arch,files:Object.fromEntries(files.map(p=>[p,sha(p)]))}),constitutionHash:CONSTITUTION_HASH,policyHash:sha('core/v2/policy.ts')};}
export function validateScope(raw:unknown){const s=scopeSchema.parse(raw),i=continuousIdentity();if(s.runtimeHash!==i.runtimeHash||s.constitutionHash!==i.constitutionHash||s.policyHash!==i.policyHash||s.permissionHash!==digest(LOCAL_PERMISSION)||digest(s.forbidden)!==digest(FORBIDDEN)||new Set(s.allowedEvents).size!==s.allowedEvents.length||new Set(s.allowedEffects).size!==s.allowedEffects.length||s.plannerTimeoutMs>=s.leaseMs||s.maxCostPerCycleMicros>s.maxCostPerWindowMicros||Date.parse(s.expiresAt)<=Date.parse(s.issuedAt)||s.minimumPriorDecisions<8&&!s.organismId.startsWith('fixture-'))throw Error('Continuous scope identity/limits mismatch');return s;}
