import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {z} from 'zod';
import {CONSTITUTION,CONSTITUTION_HASH,digest} from '../core/v2/identity.ts';
import type {Permissions} from '../core/v2/contracts.ts';
const sha=(p:string)=>createHash('sha256').update(readFileSync(new URL('../'+p,import.meta.url))).digest('hex');
export const modeSchema=z.object({id:z.literal('GENESIS_FIRST_AWAKENING_V1'),version:z.literal('1.0.0'),authorization:z.literal('NOT_AUTHORIZED'),maximumCycles:z.literal(1),expectedDecisions:z.literal(7),maximumProviderAttempts:z.literal(1),maximumCostMicros:z.literal(50000),maximumInputTokens:z.literal(12000),maximumOutputTokens:z.literal(1200),timeoutMs:z.literal(25000),leaseMs:z.literal(60000),automaticRetries:z.literal(0),executionLock:z.literal('CLOSED'),scheduleEnabled:z.literal(false),biologicalMode:z.literal('SAVED-OBSERVATION-ONLY'),allowedLocalEffects:z.tuple([z.literal('local_reflection'),z.literal('local_artifact')]),allowedOutcomes:z.tuple([z.literal('ABSTAIN'),z.literal('DEFER'),z.literal('REQUEST_ASSISTANCE'),z.literal('PROPOSAL')]),forbiddenEffects:z.array(z.string()),providerAdmission:z.literal('PENDING')}).strict();
export function awakeningMode(){const m=modeSchema.parse(JSON.parse(readFileSync(new URL('../config/first-awakening-v1.json',import.meta.url),'utf8')));if(m.forbiddenEffects.join('|')!=='biological_advance|biological_stimulation|neural_step|fly_runtime|wallet_rpc|wallet_signing|transfers|trading|token_launch|clawpump|purchases|hiring|external_message|social_posting|internet|browser_automation|shell|filesystem_execution|unadmitted_external_api|scheduler|second_cycle')throw Error('Forbidden scope changed');return m;}
export function runtimeIdentity(){
 const files=['runtime/deployment/consumer.ts','runtime/deployment/consumer-cli.ts','runtime/deployment/config.ts','runtime/deployment/log.ts','runtime/deployment/schema.ts','runtime/deployment/install.ts','runtime/deployment/installer-cli.ts','runtime/deployment/readiness.ts','runtime/deployment/http-server.ts','runtime/deployment/release.sql','runtime/deployment/roles.sql','runtime/deployment/catalog-baseline.json','runtime/deployment/catalog-installed.json','runtime/provider-role-grants.sql','runtime/provider-smoke.ts','server/reasoning/inspection.ts','server/reasoning/contracts.ts','server/reasoning/factory.ts','server/reasoning/request.ts','server/reasoning/control.ts','server/reasoning/store.ts','runtime/provider-integration-schema.sql','server/provider-disclosure.ts','runtime/operator-cli.ts','runtime/operator-role-grants.sql','core/v2/disclosure.ts','server/disclosure-store.ts','server/operator-auth.ts','server/operator-control.ts','server/operator-transaction.ts','runtime/operator-schema-v1.sql','core/v2/continuous.ts','server/continuous.ts','server/continuous-worker.ts','server/continuous-spec.ts','server/continuous-authority.ts','runtime/continuous-schema.sql','package.json','package-lock.json','runtime/main.ts','runtime/http.ts','runtime/service.ts','runtime/config.ts','runtime/scheduler.ts','server/store.ts','server/life-store-v1.ts','core/v2/biology.ts','core/v2/contracts.ts','core/v2/identity.ts','core/v2/context.ts','core/v2/memory.ts','server/memory-store.ts','core/v2/cycle.ts','core/v2/life-state.ts','server/assistance-intake.ts','core/v2/operations.ts','core/v2/operational-context.ts','core/v2/planner.ts','core/v2/policy.ts','core/v2/intents.ts','server/intent-journal.ts','server/saved-provenance.ts','server/commit-v2.ts','server/provider-control.ts','server/one-shot-spec.ts','server/one-shot-authority.ts','server/one-shot.ts','server/awakening-event.ts','server/provider-admission.ts','runtime/preparation-schema.sql','runtime/one-shot-schema.sql','config/first-awakening-v1.json','config/first-awakening-event.schema.json'];
 return {version:'runtime-v1-oneshot-1.0.8',sha256:digest({nodeVersion:process.version,platform:process.platform,architecture:process.arch,files:Object.fromEntries(files.map(p=>[p,sha(p)]))})};
}
export function identities(){return {runtime:runtimeIdentity(),constitution:{version:CONSTITUTION.version,hash:CONSTITUTION_HASH},policy:{version:'policy-v1',hash:sha('core/v2/policy.ts')},mode:{version:'1.0.0',hash:digest(awakeningMode())},event:{version:1,hash:sha('config/first-awakening-event.schema.json')}};}
const identity=z.object({version:z.string(),hash:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const permissionSchema=z.object({execution:z.literal(true),localArtifacts:z.boolean(),llm:z.boolean(),internet:z.literal(false),communication:z.literal(false),financial:z.literal(false),maxCostMicros:z.number().int().min(0).max(50000),maxAttempts:z.number().int().min(0).max(1)}).strict();
export const grantSchema=z.object({id:z.string().min(1).max(100),organismId:z.string().min(1),runtime:z.object({version:z.string(),sha256:z.string()}).strict(),constitution:identity,policy:identity,mode:identity,event:z.object({version:z.literal(1),hash:z.string()}).strict(),permission:permissionSchema,permissionHash:z.string(),maximumCycles:z.literal(1),planner:z.object({identity:z.string().min(1),provider:z.string().nullable(),model:z.string().nullable(),admissionHash:z.string().nullable()}).strict(),maximumProviderAttempts:z.literal(1),maximumCostMicros:z.number().int().min(0).max(50000),maximumInputTokens:z.number().int().min(1).max(12000),maximumOutputTokens:z.number().int().min(1).max(1200),allowedLocalEffects:z.array(z.enum(['local_reflection','local_artifact'])),forbiddenEffects:z.array(z.string()),issuedAt:z.string().datetime(),expiresAt:z.string().datetime(),issuer:z.string().min(1),authorizationReference:z.string().min(1),stateRevision:z.number().int().nonnegative(),lifeRevision:z.number().int().nonnegative(),expectedDecisionCount:z.literal(7)}).strict();
export type OneShotGrant=z.infer<typeof grantSchema>;
export function validateGrant(input:unknown):OneShotGrant{
 const g=grantSchema.parse(input),i=identities(),m=awakeningMode();
 for(const k of ['runtime','constitution','policy','mode','event'] as const)if(digest(g[k])!==digest(i[k]))throw Error('Grant identity mismatch: '+k);
 if(g.permissionHash!==digest(g.permission)||g.permission.maxCostMicros>g.maximumCostMicros||digest(g.forbiddenEffects)!==digest(m.forbiddenEffects)||new Set(g.allowedLocalEffects).size!==g.allowedLocalEffects.length)throw Error('Grant scope mismatch');
 if(Date.parse(g.issuedAt)>Date.now()||Date.parse(g.expiresAt)<=Date.parse(g.issuedAt))throw Error('Invalid grant time');
 if(g.permission.llm?(!g.planner.provider||!g.planner.model||!g.planner.admissionHash||g.permission.maxAttempts!==1):g.planner.provider!==null||g.planner.model!==null||g.planner.admissionHash!==null)throw Error('Planner admission mismatch');
 return g;
}
export function makeGrant(input:{id:string;organismId:string;stateRevision:number;lifeRevision:number;issuer:string;authorizationReference:string;permission:Permissions;planner:OneShotGrant['planner'];at:string;expiresAt:string}):OneShotGrant{
 const m=awakeningMode();return validateGrant({id:input.id,organismId:input.organismId,...identities(),permission:input.permission,permissionHash:digest(input.permission),maximumCycles:1,planner:input.planner,maximumProviderAttempts:1,maximumCostMicros:m.maximumCostMicros,maximumInputTokens:m.maximumInputTokens,maximumOutputTokens:m.maximumOutputTokens,allowedLocalEffects:m.allowedLocalEffects,forbiddenEffects:m.forbiddenEffects,issuedAt:input.at,expiresAt:input.expiresAt,issuer:input.issuer,authorizationReference:input.authorizationReference,stateRevision:input.stateRevision,lifeRevision:input.lifeRevision,expectedDecisionCount:7});
}
