"""Evidence synthesis only; no runtime operators or neural parameters."""
from common import *
import itertools
ARTICLE='https://elifesciences.org/articles/85756'
A=load(HERE/'ANATOMY_AUDIT.json');M=load(HERE/'MEASUREMENT_AUDIT.json')
hemibody={'SMP353':['424443911'],'SMP354':['389307767','390003153','5813010748'],'SMP108':['298258513','361445621']}
roots=[]
for typ,ns in A['groups'].items():
 for n in ns:
  roots.append({'root_id':n['root_id'],'cell_type':n['cell_type'],'hemibrain_type':n['hemibrain_type'],'side':n['side'],'anatomical_identity_confidence':'pinned annotation; no new morphology registration performed','candidate_hemibrain_body_ids':hemibody.get(typ),'one_to_one_hemibrain_body_id':None,'driver_membership':None,'recorded_cell_identity':None,'receptor':None,'target_specific_sign':None,'functional_crosswalk_confidence':'source-class supported' if typ=='MBON07' else 'type/morphology candidate only; physiological individual unresolved','annotation_transmitter':n['known_nt'],'predicted_transmitter':n['top_nt'],'sign_not_inferred_from_transmitter':True})
write('CROSSWALK.json',{'dataset':A['dataset'],'roots':roots,'hemibrain_body_ids_source':'85756 Figure3-supplement1 image (manually inspected) and 79042 Supplement1 K172/K191/K5','hemibrain_other_broad_driver_candidates':{'SLP399':['266187559','481731074'],'SMP348':['298591130','5813039910'],'SLP400':['296199149','326886609','484134987']},'SMP354_alias_evidence':'v3.1.0 annotation carries cell_type CB3112 and hemibrain_type SMP354 on six roots; this is an anatomical annotation alias, not physiological driver equivalence','driver_cautions':['SS33917 anatomy and behavior; prose SS33197 discrepancy remains','R64A11-LexA is broader than the split driver; 17 recordings are not 17 identified SMP353/SMP354 roots','SS67249 stochastic one-to-three-cell subset, includes a morphology resembling SMP353 and off-target cells; not suitable for the published behavioral experiments'],'local_sites':'Exact starting edge: 4 SMP_L and 7 SLP_L contacts. No per-contact xyz or registered electrical compartment assignment in aggregate graph. Paper hemibrain morphology is separate evidence.','root_ownership':'References only to canonical pinned nodes/anatomy; no new synapse ownership','hemisphere_transfer':'Published hemibrain analysis uses right hemisphere; starting FAFB pair left. Matching cell class does not identify a physiological homolog or transfer a gain.'})
preps=[
 {'id':'stage1','measurement':'dimensionless model rates/plastic efficacy','animal_id':None,'driver':None,'preparation':'frozen artificial cue/PAM input, scalar model with declared normalized contacts','units':'model-specific','source':'../genesis-brain-spec-v0.2/STAGE5_READINESS.md'},
 {'id':'connectome','measurement':'chemical contacts / neuropil aggregate rows','animal_id':'single FAFB adult female specimen; not physiological animals','driver':None,'preparation':'fixed EM v783, annotations v3.1.0; hemibrain distinct specimen','units':'contacts','source':'ANATOMY_AUDIT.json'},
 {'id':'alpha1_stimulation','measurement':'UpWiN baseline-subtracted somatic voltage','animal_id':None,'cell_id':None,'driver':'MB310C>Chrimson88-tdTomato; R64A11-LexA target','preparation':'in-vivo current clamp; 48–72 h retinal; female per general methods; held near -60 mV with typically <10 pA bias','units':'mV','sampling_hz':10000,'filter_hz':5000,'stimulus':'625 nm 17 mW/mm²; 10 ms pulse','baseline_window':None,'source':'85756 Fig4B, Methods and genotype table; source-data2'},
 {'id':'upwin_population','measurement':'population GCaMP6s fluorescence, dendrite/axon junction','animal_id':None,'cell_id':None,'driver':'R64A11-LexA target; G0239 and/or MB310C stimulation','preparation':'dissected female brain 3–7 d, 20 C, 2 mM external calcium','units':'deltaF/F','sampling_hz_method_approx':1.07,'export_grid_seconds':1,'stimulus':'660 nm 12 µW/mm²; 1 s, nine trials at 30 s intervals','baseline':'background subtracted; preceding 5 s baseline F','source':'85756 Fig4C; mean/SEM only, not per-animal data'},
 {'id':'conditioning_recall','measurement':'UpWiN subthreshold odor-evoked voltage','animal_id':None,'cell_id':None,'driver':'SS67249 GFP; R58E02-LexA ChrimsonR broad reward DANs incl alpha1/beta1','preparation':'in-vivo whole-cell 48–72 h; holding near -60 mV; 1% headspace air dilution','units':'baseline-subtracted mV, 0–1.2 s mean','sampling_hz':10000,'stimulus':'1 min paired odor, 120 1 ms pulses at 2 Hz; reciprocal OCT/MCH; 1 s recall odors','baseline_window':None,'source':'85756 Fig5 and supplement2; complete within-row scalar pairing; no stable external animal IDs'},
 {'id':'behavior','measurement':'wind-relative orientation, turning, walking speed, area-normalized radial displacement; other endpoints separately labeled','animal_id':None,'driver':'SS33917/SS33918 activation; figure-specific DAN drivers for Fig1','preparation':'intact adult females 4–10 d; fed vs 40–48 h starved; four-arm arena; wind and arista controls','units':['degrees','degrees/s','mm/s','dimensionless delta(r/50mm)^2','cosine'], 'sampling_hz_video':30,'source':'85756 Fig1/6 with supplements; trial/trajectory summaries and movie locators, not complete tracked XY streams'},
 {'id':'causal_interventions','measurement':'TNT upwind response; shibire binary odor distribution at 25/32 C; optogenetic kinematics','animal_id':None,'driver':'SS33917 TNT/shibire; SS33917/SS33918 CsChrimson','preparation':'whole-fly behavior; sugar conditioning 1-day recall for Fig7; controls differ by assay','units':'published assay-specific quantities','source':'85756 Fig6/7; shibire upwind endpoint unavailable at restrictive temperature'},
 {'id':'alpha1_conditioning_external','measurement':'MBON-alpha1 odor-evoked spikes','animal_id':None,'cell_id':None,'driver':'MB319C mScarlet; PAM-alpha1 MB043-split-LexA ChrimsonR','preparation':'79042 in-vivo 48–72 h retinal, near -60 mV typically <100 pA; 2% headspace for non-second-order experiment','units':'baseline-subtracted odor-evoked spike count over 1.2 s; separate mean instantaneous rate has 50 ms Gaussian smoothing','source':'79042 Fig3 supplement2, acquired original zip, not the 85756 UpWiN voltage preparation'}]
bridges=[]
for a,b in itertools.combinations([p['id'] for p in preps],2):
 if a=='stage1':cat='INCOMPATIBLE';why='Direct numerical composition is incompatible without an independently identified observation/physiology mapping; conceptual anatomy/plasticity analogy is not a measured transfer.'
 elif a=='connectome':cat='TRANSFER REQUIRES ASSUMPTION';why='Distinct fixed female specimen; root-to-recording/driver crosswalk and active physiological state unresolved.'
 elif {a,b}=={'behavior','causal_interventions'}:cat='DIRECTLY COMPATIBLE';why='Within the SAME documented figure-specific intact behavioral assay, intervention and control compare the same measured endpoint; this does not join different drivers, temperatures or individual flies.'
 elif {a,b}=={'alpha1_stimulation','conditioning_recall'}:cat='TRANSFER REQUIRES ASSUMPTION';why='Similar electrical technique, but broad R64A11 versus stochastic SS67249 cells; no demonstrated same-cell overlap and different stimuli.'
 elif 'upwin_population' in (a,b):cat='INCOMPATIBLE';why='Direct numerical pooling of dissected-brain deltaF/F with voltage/spikes/behavior is invalid; observation conversion and matching local cell population unmeasured.'
 elif {a,b}=={'conditioning_recall','alpha1_conditioning_external'}:cat='TRANSFER REQUIRES ASSUMPTION';why='Same pairing pulse timing and reciprocal odors, but different DAN drivers (broad58E02 vs PAM-alpha1), odor dilution1% vs2%, electrical bias and source/target cells, spike count vs mV. Not simultaneous or numerically composable.'
 else:cat='UNKNOWN';why='No same-animal neural/behavioral transfer or compatible individual identities established; observational analogy does not supply a measurement bridge.'
 bridges.append({'from':a,'to':b,'classification':cat,'scope':'directly joining the actual measurements','reason':why})
write('PREPARATION_COMPATIBILITY.json',{'preparations':preps,'bridges':bridges,'within_assay_direct_bridges':[{'from':'Fig5 row pre','to':'same Fig5 row post','classification':'DIRECTLY COMPATIBLE','scope':'four scalar values paired within one source row only'},{'from':'Fig4B alpha1 stimulation','to':'same current-clamp voltage record','classification':'DIRECTLY COMPATIBLE','scope':'recorded broad-driver cell, not assigned root'}],'composite_pathway_created':False})
items=[
 ('defensible source identity','SUPPORTED AT CELL-CLASS / PINNED-ROOT LEVEL','MBON-alpha1/MBON07 class and starting root identified; no recording-to-specific-root identity.'),
 ('defensible downstream target identity','PARTIAL','SMP353 hemibrain body424443911 and FAFB type match; CB3112/SMP354 annotation alias supported. Actual responders and recall cells not assigned to these roots.'),
 ('directional anatomy','SUPPORTED NARROWLY','11 starting contacts; candidate convergence/recurrence counted in pinned graph. Counts do not establish efficacy.'),
 ('target-scoped physiological sign','UNRESOLVED FOR REQUIRED ROOTS','Inhibitory Vm response in4/17 broad-driver cells. No responder-to-SMP353/SMP354/root or target receptor crosswalk.'),
 ('measurable downstream neural variable','SUPPORTED WITH OBSERVATION LIMITS','Baseline-subtracted UpWiN somatic mV measured; calcium separate. No gain, latency, current or model-rate conversion identified.'),
 ('conditioning-compatible evidence','PARTIAL','Reciprocal UpWiN mV change acquired; separate alpha1 spike suppression acquired. DAN-driver/dilution/recording differences prevent causal numerical composition.'),
 ('independently action-related biological variable','SUPPORTED AT DRIVER/ASSAY LEVEL','Wind-relative turn, speed and displacement measured in intact flies; no behavior from a specific root or Vm mapping.'),
 ('causal intervention evidence','PARTIAL','Driver activation and TNT/Shi experiments exist. Root specificity and preserved upstream learning/sensory function for the complete route not shown; restrictive-temperature upwind control fails.'),
 ('sufficient preparation compatibility','NOT YET','No source-root-to-recorded-target-to-behavior preparation chain; physiological source papers differ in units and conditions.'),
 ('sufficient raw data for prospective thresholds and held-out validation','PARTIAL','Scalar recall values and cell-mean Vm traces available; Ca/recall mean waveforms lack animal traces, Fig4 animal labels inconsistent, full trajectories unavailable. Do not define thresholds or splits here.')]
write('READINESS.json',{'classification':'PARTIAL ROUTE SUPPORT — TARGETED EVIDENCE STILL REQUIRED','assessment':[{'item':i+1,'requirement':a,'status':b,'evidence':c} for i,(a,b,c) in enumerate(items)],'stage5_authorized':False,'stage5_protocol':None,'neural_runs':0,'fitting':False,'capability_promotions':[],'required_evidence':['Responding/recall cell morphology or transcript/driver crosswalk to identified SMP353/CB3112-SMP354 homologs','Target-scoped sign/receptor and electrical transmission under compatible preparation, including nonresponders','Original trial/animal identities, event/baseline metadata, ROI masks and exclusion lineage; resolve workbook labels/sample counts','Compatible source/downstream learning measurements isolating alpha1 contribution from beta1 and background routes','Route-specific intervention evidence preserving relevant upstream learning, sensory and locomotor responses; independent neural/action observation relationship'],'forbidden_inferences':['contact count = conductance','glutamate = universally inhibitory','Ca flat = no Vm inhibition','SMP name = identified responder','Stage1 rate = mV','UpWiN mV = movement probability','behavioral driver activation = root-specific voluntary choice']})
write('EVIDENCE_LEDGER.json',{'spec_registry_sha256':SPEC_SHA,'spec_package_sha256':PACKAGE_SHA,'admitted_to_spec':False,'claims':[
 {'id':'anatomy.starting-route','category':'BIOLOGICAL FACT','scope':'pinned proofread chemical-contact graph','value':11,'unit':'contacts','source':'ANATOMY_AUDIT.json','physiology':None},
 {'id':'physiology.broad-driver.alpha1','category':'BIOLOGICAL FACT','scope':'published current-clamp sample','responders':4,'sampled_neurons':17,'animals_reported':12,'variable':'baseline-subtracted membrane potential mV','target_roots':None,'receptor':None,'source':'85756 Fig4B'},
 {'id':'recall.upwin','category':'BIOLOGICAL FACT','scope':'SS67249 sampled cells after broad-PAM conditioning','source':'MEASUREMENT_AUDIT.json','alpha1_only_attribution':False},
 {'id':'disinhibition.route','category':'HYPOTHESIS','scope':'alpha1 decrease could disinhibit particular UpWiNs given their background excitation and target sign','numerical_operator':None,'source':'85756 discussion; 79042 conditional mechanism'},
 {'id':'action.driver-assay','category':'BIOLOGICAL FACT','scope':'population-driver manipulation changes published wind-related kinematics under declared intact-fly conditions','root_action_operator':None,'source':'85756 Fig6/7'},
 {'id':'root-sign','category':'HYPOTHESIS','scope':'SMP353/SMP354 root-specific alpha1 inhibitory sign not established by current crosswalk','value':None,'source':'CROSSWALK.json'},
 {'id':'audit-arithmetic','category':'ENGINEERING ASSUMPTION','scope':'exact source numeric means/SEM and graph sums only; unknowns represented as null','fitted_parameters':[]},
 {'id':'genesis-mapping','category':'GENESIS PRODUCT MAPPING','scope':'none authorized','value':None}], 'canonical_anatomy_ownership':'reference only','new_neural_operators':[]})
print('Evidence crosswalk, compatibility and ten-item readiness written')
