"""Materialize the diagnostic evidence audit, not a Brain Spec update."""
from common import save

def evidence():
    # unknown is explicit; no coefficients below enter a neural model.
    return [
      dict(id='E01',doi='10.1038/nature24626',source='https://doi.org/10.1038/nature24626',
        population='LPLC2; T4/T5; LPi4-3',preparation='female adult D. melanogaster, calcium 2–5 d, 21.8 C; GCaMP6f; single axon and population assays distinguished',
        data='Published figures and frozen full-text XML; original imaging recordings/code on request, not obtained',
        measured='Layer-specific outward arbors; small outward bars evoke responses; combined arms yield supra-additive calcium; inward orthogonal motion suppresses; LPi4-3 optogenetics suppresses weak bar response.',
        quantitative='RF mapping: 5 degree grid, 5–20 degree disk, 10 degree/s edge; bar assay 10 degree narrow versus 60 degree wide, 20 degree/s; n=10 neurons/7 flies for bar-direction experiments.',
        model_not_measurement='Radial opponency mechanism is constrained; root-specific gain, synaptic delay, membrane compartments and calcium-to-voltage inverse are not identified.',
        crosswalk='LPLC2/T4/T5 class correspondence supported; LPi4-3 to FlyWire LPi11 supported by E09; no imaging ROI to selected root assignment',
        classification='experimentally constrained',unknown=['local voltage state number','interbranch electrical coupling','root-specific RF center','LPi→LPLC2 receptor map']),
      dict(id='E02',doi='10.7554/eLife.17421',source='https://elifesciences.org/articles/17421',
        population='upward T4 terminals; L2',preparation='adult D. melanogaster, GCaMP6m two-photon, column-targeted optical stimulation; 25 C rearing; sex/age not specified in retrieved methods',
        data='Published quantitative text/figures; no raw per-fly recordings analyzed',
        measured='Spatially separated preferred-direction enhancement and null-direction suppression; positive isolated-column flash responses.',
        quantitative='1176 ms flashes; T4 neighbors ~50%, outer ring ~25% of center (10 cells/10 flies); L2 <30% and <12% (23 cells/6 flies). 472 ms pulses; enhancement peaks near 500 ms onset separation, suppression relaxes beyond 500 ms.',
        model_not_measurement='Published three-input multiplicative/divisive detector is a proposed model. Pulse lag is not a measured 500 ms membrane tau.',
        crosswalk='T4 upward/layer 3 class only, not root-specific recordings',classification='experimentally constrained',unknown=['absolute voltage gain','root physiological time constants']),
      dict(id='E03',doi='10.1016/j.cub.2021.09.072',source='https://doi.org/10.1016/j.cub.2021.09.072',
        population='T4/T5',preparation='adult D. melanogaster whole-cell electrophysiology; sex/age and cell-level archive metadata not verified here',
        data='Figshare article 16663705 v1; 6,320,065,220-byte Figure2.zip listed, not processed',
        measured='Composite ON/OFF receptive fields and responses to non-preferred contrast motion.',quantitative='Per-cell .result arrays with positions, durations, widths, vals are advertised; no new numerical measurements claimed.',
        model_not_measurement='Authors fitted biophysical model is not an independently measured receptor/parameter map.',
        crosswalk='class-level; recorded cells not matched to selected v783 roots',classification='experimentally constrained',unknown=['held-out errors in this diagnostic','root-specific physiology']),
      dict(id='E04',doi='10.1016/j.cub.2024.10.053',source='https://pmc.ncbi.nlm.nih.gov/articles/PMC11834764/',
        population='Mi1/Tm3 and T4a/T5a; additional early visual types',preparation='nonvirgin female D. melanogaster 2–7 d, 25 C; GCaMP6f T4/T5',
        data='Dryad 10.5061/dryad.t1g1jwtbs version 4 metadata saved; API downloads 401, public file_stream 403; DANDI 001205 raw alternative identified but unprocessed',
        measured='Isolated moving bars activate both contrast channels; non-preferred response delayed and speed tuning differs; dense stimuli differ. Processing depends on stimulus statistics.',
        quantitative='Fig7A T4 10/T5 9 flies; Fig7B T4 11/T5 9; not silently pooled. No raw held-out fit completed.',
        model_not_measurement='LNL sparsity model is explanatory, not a measured synaptic operator.',crosswalk='T4a/T5a class; not all subtypes or exact roots',
        classification='experimentally constrained',unknown=['numerical response family validated here','physiological adaptation state equation']),
      dict(id='E05',doi='10.1038/s41467-021-24986-w',source='https://www.nature.com/articles/s41467-021-24986-w',
        population='Tm1/Tm2/Tm4/Tm9, CT1, T5',preparation='female D. melanogaster 1–7 d; in vivo right optic lobe; two-photon calcium, GCaMP6f; CDM and control separated',
        data='Publisher MOESM4 XLS saved and hashed; all 70 control ROIs/7 fly IDs analyzed in Fig7g; labelled degree widths summarized separately',
        measured='Contrast-opponent spatial responses in upstream cells; calcium observation depends on baseline. Source measurements are not synaptic currents.',
        quantitative='See INDEPENDENT_RESULTS.json: read-only workbook extraction with exact sheet/ranges and leave-one-fly-out observations.',
        model_not_measurement='Passive-dendrite/conductance model in paper is a hypothesis. Tm9 calcium decrement is not inhibitory transmitter evidence.',
        crosswalk='class-level Tm9/T5; no source ROI→FAFB root identity',classification='experimentally measured',unknown=['synaptic gain','root receptor map','T4/T5 neural calibration']),
      dict(id='E06',doi='10.1038/s41586-025-09276-5',source='https://www.nature.com/articles/s41586-025-09276-5',
        population='Mi1/T4 anatomy, H2 physiology, female compound eye',preparation='female FAFB EM; separate female 6–7 d microCT eyes; female 2–3 d H2 whole-cell physiology',
        data='Frozen eye-map XML and repository tree pinned 99d2a43123db636cedb55af9ff31a59657e7d17e; numerical eye map not applied to selected roots',
        measured='Nonuniform visual sampling, curved local preferred directions; anatomical eye-grid mapping supported by H2 measurements.',
        quantitative='Anatomical centers mapped into eye viewing directions; published medulla↔eye convention includes left-right flip. Approximate separate-fly registration, worse at periphery.',
        model_not_measurement='Interpolation/registration is an approximation; rectangular 5 degree grid is not an eye map.',
        crosswalk='same FAFB volume supports anatomical correspondence; CATMAID skeleton/column→v783 root→microCT→screen chain remains unvalidated for this extraction',
        classification='experimentally constrained',unknown=['selected-root retinal angles','selected-root screen preferred direction','per-root alignment uncertainty']),
      dict(id='E07',doi='10.1016/j.cub.2022.12.014',source='https://www.sciencedirect.com/science/article/pii/S0960982222019145',
        population='LPLC2',preparation='adult D. melanogaster tethered non-flying imaging, GCaMP7f; exact sex/age not verified from accessible methods',
        data='Publisher indexed primary text; direct full-text retrieval 403; no raw recording values processed',
        measured='Responses to translating spots as well as looms; local LP/lobula/axon calcium assays reported.',
        quantitative='No numerical calibration extracted; assay and speed distinctions retained.',
        model_not_measurement='Translation-response hypotheses do not identify inhibitory delay or local voltage coupling. Local calcium is not automatically a local electrical compartment.',
        crosswalk='class only; lobula input name Tm5Y not equated with Tm5f or TmY5a without independent crosswalk',
        classification='weakly constrained',unknown=['quantitative local-state comparison','root input crosswalk','local voltage model']),
      dict(id='E08',doi='10.1016/j.cell.2015.06.035',source='https://doi.org/10.1016/j.cell.2015.06.035',
        population='LPi and lobula plate tangential cells',preparation='adult D. melanogaster; optogenetic/electrophysiological pathway experiments; root-specific preparation unavailable',
        data='Primary article mechanism identified; no source recordings processed',
        measured='Opposing-motion integration with glutamatergic inhibitory LPi transmission onto tested tangential targets.',
        quantitative='No receptor conductance values imported.',model_not_measurement='LPTC GluCl evidence does not assign every LPLC2 postsynaptic receptor.',
        crosswalk='LPi functional names audited with E09; target mismatch retained',classification='experimentally constrained',unknown=['LPLC2 root receptor identity','LPLC2-specific LPi09 sign']),
      dict(id='E09',doi='10.1038/s41586-024-07981-1',source='https://doi.org/10.1038/s41586-024-07981-1',
        population='FlyWire optic-lobe annotated classes',preparation='single adult female FAFB anatomical specimen',
        data='Pinned v783 proofread contacts and v3.1.0 annotation, reused read-only; Stage4 CROSSWALK.json',
        measured='Anatomical chemical contacts and class labels; LPi11 corresponds to LPi4-3 and LPi09 to LPi3-4.',
        quantitative='Full retained/omitted and effective contacts in ANATOMY_AUDIT.json.',model_not_measurement='Contact counts do not identify conductance, receptor or delay; proofread aggregate rows do not localize individual synapses on branches.',
        crosswalk='high anatomical/class confidence in frozen scope; physiology root transfer unresolved',classification='experimentally measured',unknown=['subcellular synapse locations in aggregate file','unknown-edge physiological sign']),
      dict(id='E10',doi='10.7554/eLife.74937',source='https://elifesciences.org/articles/74937',
        population='L1/L2/L3',preparation='adult D. melanogaster calcium/behavior experiments; assay sex/age not reverified here',
        data='Primary published figures/text; no source recording fit',
        measured='Differential contrast and luminance signals reach both ON/OFF pathways.',
        quantitative='10 s luminance steps in published assay; separate cell classes, no shared model tau inferred.',
        model_not_measurement='Authors sigmoid coefficients are observation fits, not Stage4 neural gains.',
        crosswalk='class level; not selected-root physiology',classification='experimentally constrained',unknown=['absolute optical calibration in Stage4','class temporal kernels']),
      dict(id='E11',doi='10.1016/j.cub.2024.11.064',source='https://pmc.ncbi.nlm.nih.gov/articles/PMC11769683/',
        population='L1/L2 and recurrent early visual pathway',preparation='adult D. melanogaster ASAP2f voltage assay; no numeric raw-data fit here',
        data='Primary article and Dryad 10.5061/dryad.ngf1vhj4c identified; raw MAT arrays unprocessed',
        measured='Biphasic flash responses and recurrent contributions to temporal filtering.',
        quantitative='20 ms flash/120 Hz voltage sampling reported; not a membrane-tau estimate.',
        model_not_measurement='A proposed recurrent implementation is not uniquely identified by temporal traces.',
        crosswalk='class-level, not root-specific parameters',classification='experimentally constrained',unknown=['selected-root recurrent kernel','independent parameter identifiability'])
    ]

def transformations():
    entries=[
      ('physical_movie','engineering assumption','Angular stimulus definitions and normalized intensities in frozen Movie class','Calibrated photons, optical blur, display spectral/refresh transfer absent',['E01','E10']),
      ('screen_geometry','engineering assumption','Planar grid, 5 degree spacing, fixed cardinal subtype axes','Eye curvature, chiasm convention, nonuniform sampling and screen projection not audited',['E06']),
      ('local_intensity','engineering assumption','Two point samples around each assigned root column','RF extent, neighboring-column integration, edge optics, luminance adaptation not represented',['E02','E05','E10']),
      ('polarity_preprocessing','engineering assumption','Absolute positive/negative contrast about 0.5, strict T4 ON/T5 OFF','Nonpreferred polarity and signed baseline changes deleted; stimulus-statistics history absent',['E03','E04','E05']),
      ('motion_correlation','engineering assumption','Rectified two-site antisymmetric correlation, equal 50 ms delays','Separable flash responses cancel; offset enhancement/suppression subfields absent',['E02','E03']),
      ('t4_t5_activity','engineering assumption','Synthetic motion into scalar leaky state, common 50 ms tau','Retained anatomical afferents lack operators; calcium/voltage distinction, class kinetics unknown',['E02','E03','E04','E05','E11']),
      ('root_type_column_mapping','experimentally constrained','Pinned string roots, annotation and column references; conflicting metadata excluded','Exact physiological ROI correspondence unresolved; aggregate root/column is not RF',['E06','E09']),
      ('column_to_visual_direction','unidentified','Frozen grid axis-to-preferred-direction convention not calibrated','All 24 group radial alignments negative under those axes; retinal meaning remains unresolved',['E01','E06']),
      ('anatomical_transmission','weakly constrained','Supported class signs for T4/T5 and LPi11; LPi09 inhibition is hypothesis','Unknown retained edges numerically excluded; counts do not imply efficacy or receptor effects',['E01','E08','E09']),
      ('normalization','engineering assumption','Count/full target input or frozen retained sensitivity arm','Relative physiological gains, omitted ongoing conductance and baseline not identified',['E09']),
      ('lpi_lplc2_integration','engineering assumption','One scalar per neuron, instantaneous signed contact sum before rectification','Input layer/branch identity lost after summation; no independently measured local coupling or delay',['E01','E07']),
      ('lplc2_observation','unidentified','Dimensionless rate reported directly; no calcium observation operator','Indicator kinetics/baseline/saturation and local-to-axon transfer absent',['E01','E07'])
    ]
    return [dict(id=i,classification=c,frozen_operation=f,missing_or_destroyed=m,evidence=e) for i,c,f,m,e in entries]

if __name__=='__main__':
    save('EVIDENCE.json',{'status':'diagnostic only; not admitted to Brain Spec','sources':evidence()})
    save('TRANSFORMATIONS.json',{'entries':transformations(),'parameters_transferred_to_neural_models':[]})
